#!/usr/bin/env python3
"""
generate_distributed_inflow.py — Generate distributed tributary inflow for CE-QUAL-W2.

Distributes ungauged local runoff (from VIC) as lateral inflow along reservoir segments.
Creates qdt_*.npt and tdt_*.npt files (distributed tributary flow and temperature).

CRITICAL (dt_021): Avoid double-counting with CaMa-routed main channel inflow.
Only include runoff from sub-basins NOT already routed through CaMa-Flood.
The contributing area for distributed tributary = total reservoir catchment area
MINUS the contributing area of the main inflow branch(es).

Usage:
    python generate_distributed_inflow.py \
        --vic_runoff_dir /path/to/vic_result \
        --grid_json /path/to/reservoir_grid.json \
        --met_file met_wb1.npt \
        --contributing_area_km2 500 \
        --main_inflow_area_km2 5000 \
        --start_year 2005 --end_year 2010 \
        --output_dir /path/to/output
"""

import argparse
import json
import os
import sys
from datetime import datetime, timedelta

import numpy as np


def datetime_to_jday(dt):
    """Convert datetime to decimal Julian day."""
    doy = dt.timetuple().tm_yday
    frac = dt.hour / 24.0 + dt.minute / 1440.0
    return doy + frac


def process(args):
    """Main processing."""
    os.makedirs(args.output_dir, exist_ok=True)

    with open(args.grid_json) as f:
        grid = json.load(f)

    n_active = grid["n_active_segments"]

    # Estimate local runoff per segment
    # Total local catchment = contributing_area - main_inflow_area
    local_area_km2 = args.contributing_area_km2 - args.main_inflow_area_km2
    if local_area_km2 < 0:
        local_area_km2 = 0

    area_per_segment_km2 = local_area_km2 / max(1, n_active)
    area_per_segment_m2 = area_per_segment_km2 * 1e6

    # Generate time series (daily for simplicity)
    n_years = args.end_year - args.start_year + 1
    n_days = n_years * 365  # approximate

    start_dt = datetime(args.start_year, 1, 1)
    jdays = np.array([datetime_to_jday(start_dt + timedelta(days=d)) for d in range(n_days)])

    # Estimate runoff rate (mm/day) with seasonal variation
    # Simple sinusoidal: peak in summer (JDay ~180), trough in winter
    mean_runoff_mm = args.mean_runoff_mm if args.mean_runoff_mm else 2.0  # mm/day
    seasonal_amplitude = 0.7
    runoff_mm = mean_runoff_mm * (1 + seasonal_amplitude * np.sin(2 * np.pi * (jdays - 90) / 365))
    runoff_mm = np.clip(runoff_mm, 0, None)

    # Convert to m^3/s per segment
    q_per_segment = runoff_mm * area_per_segment_m2 / (86400 * 1000)  # mm/day -> m^3/s

    # Write distributed tributary flow file
    qdt_path = os.path.join(args.output_dir, "qdt_br1.npt")
    with open(qdt_path, "w") as f:
        f.write("$Distributed tributary flow — generated by HydroCraft\n")
        f.write("$JDAY          QDT\n")
        for i in range(len(jdays)):
            f.write(f"{jdays[i]:10.3f}{q_per_segment[i]:10.4f}\n")

    # Write distributed tributary temperature file
    tdt_path = os.path.join(args.output_dir, "tdt_br1.npt")
    # Use air temperature if met file available
    if args.met_file and os.path.isfile(args.met_file):
        met_jdays, met_tair = [], []
        with open(args.met_file) as mf:
            for line in mf:
                if line.startswith("$") or line.strip() == "":
                    continue
                parts = line.split()
                if len(parts) >= 2:
                    try:
                        met_jdays.append(float(parts[0]))
                        met_tair.append(float(parts[1]))
                    except ValueError:
                        continue
        met_jdays = np.array(met_jdays)
        met_tair = np.array(met_tair)
        t_inflow = np.clip(0.75 * np.interp(jdays, met_jdays, met_tair) + 3.0, 0.5, 35.0)
    else:
        t_inflow = np.full(len(jdays), 15.0)

    with open(tdt_path, "w") as f:
        f.write("$Distributed tributary temperature — generated by HydroCraft\n")
        f.write("$JDAY          TDT\n")
        for i in range(len(jdays)):
            f.write(f"{jdays[i]:10.3f}{t_inflow[i]:10.3f}\n")

    result = {
        "status": "success",
        "qdt_file": qdt_path,
        "tdt_file": tdt_path,
        "n_timesteps": len(jdays),
        "local_area_km2": round(local_area_km2, 1),
        "area_per_segment_km2": round(area_per_segment_km2, 2),
        "mean_q_per_segment_m3s": round(float(np.mean(q_per_segment)), 4),
    }
    print(json.dumps(result, indent=2))
    return 0


def main():
    parser = argparse.ArgumentParser(description="Generate distributed tributary inflow for W2")
    parser.add_argument("--vic_runoff_dir", help="VIC result directory")
    parser.add_argument("--grid_json", required=True)
    parser.add_argument("--met_file", help="Met file for temperature estimation")
    parser.add_argument("--contributing_area_km2", type=float, required=True,
                       help="Total reservoir catchment area (km^2)")
    parser.add_argument("--main_inflow_area_km2", type=float, required=True,
                       help="Main inflow contributing area (km^2, already routed)")
    parser.add_argument("--mean_runoff_mm", type=float, default=2.0,
                       help="Mean local runoff (mm/day, default: 2.0)")
    parser.add_argument("--start_year", type=int, required=True)
    parser.add_argument("--end_year", type=int, required=True)
    parser.add_argument("--output_dir", required=True)
    args = parser.parse_args()
    sys.exit(process(args))


if __name__ == "__main__":
    main()
