#!/usr/bin/env python3
"""
generate_rvc_initial.py — Generate Raven .rvc (initial conditions) file.

Creates default initial conditions for all state variables. For cold starts,
reasonable defaults are set based on basin climate type.

Usage:
    python generate_rvc_initial.py \
        --output_dir outputs/chaohe_raven/ \
        --basin_name chaohe \
        --n_hrus 5 \
        --climate semi_humid
"""

import argparse
import json
import os
import sys
from datetime import datetime

# Default initial conditions by climate type
CLIMATE_DEFAULTS = {
    "humid": {
        "soil0": 100.0,   # mm — upper soil water
        "soil1": 50.0,    # mm — lower soil water
        "snow": 0.0,      # mm SWE
        "snow_depth": 0.0, # m
    },
    "semi_humid": {
        "soil0": 80.0,
        "soil1": 40.0,
        "snow": 0.0,
        "snow_depth": 0.0,
    },
    "semi_arid": {
        "soil0": 30.0,
        "soil1": 20.0,
        "snow": 0.0,
        "snow_depth": 0.0,
    },
    "cold": {
        "soil0": 50.0,
        "soil1": 30.0,
        "snow": 50.0,
        "snow_depth": 0.3,
    },
    "alpine": {
        "soil0": 40.0,
        "soil1": 25.0,
        "snow": 100.0,
        "snow_depth": 0.5,
    },
}


def process(args):
    climate = args.climate or "semi_humid"
    defaults = CLIMATE_DEFAULTS.get(climate, CLIMATE_DEFAULTS["semi_humid"])

    lines = []
    lines.append(f"# Raven .rvc file -- Initial conditions for {args.basin_name}")
    lines.append(f"# Climate type: {climate}")
    lines.append(f"# Generated by HydroCraft generate_rvc_initial.py")
    lines.append(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"# NOTE: These are default cold-start values.")
    lines.append(f"#   For warm start, use solution.rvc from a previous run.")
    lines.append(f"#   Recommend discarding first 1-2 years as spinup.")
    lines.append("")

    # Basin-level initial conditions
    lines.append("# Basin initial conditions")
    lines.append(f":BasinInitialConditions")
    lines.append(f"  :Attributes  ID  SURFACE_WATER  ATMOSPHERE  PONDED_WATER")
    lines.append(f"  :Units       none  mm            mm          mm")
    lines.append(f"  1  0.0  0.0  0.0")
    lines.append(f":EndBasinInitialConditions")
    lines.append("")

    # HRU-level initial conditions
    n_hrus = args.n_hrus or 1
    lines.append(f"# HRU initial conditions (all HRUs get same defaults)")
    lines.append(f":HRUStateVariableTable")

    # Header depends on soil model
    lines.append(f"  :Attributes  SOIL[0]  SOIL[1]  SNOW  SNOW_DEPTH  SNOW_LIQ  COLD_CONTENT")
    lines.append(f"  :Units       mm       mm       mm    m           mm        MJ/m2")

    for i in range(1, n_hrus + 1):
        lines.append(f"  {i}  {defaults['soil0']:.1f}  {defaults['soil1']:.1f}  "
                     f"{defaults['snow']:.1f}  {defaults['snow_depth']:.2f}  0.0  0.0")

    lines.append(f":EndHRUStateVariableTable")
    lines.append("")

    os.makedirs(args.output_dir, exist_ok=True)
    rvc_path = os.path.join(args.output_dir, f"{args.basin_name}.rvc")
    with open(rvc_path, "w") as f:
        f.write("\n".join(lines))

    return {
        "status": "success",
        "output_rvc": rvc_path,
        "climate": climate,
        "n_hrus": n_hrus,
        "defaults": defaults,
    }


def main():
    parser = argparse.ArgumentParser(description="Generate Raven .rvc initial conditions")
    parser.add_argument("--output_dir", required=True, help="Output directory")
    parser.add_argument("--basin_name", required=True, help="Basin name")
    parser.add_argument("--n_hrus", type=int, default=1, help="Number of HRUs")
    parser.add_argument("--climate", default="semi_humid",
                        help="Climate type: humid, semi_humid, semi_arid, cold, alpine")

    args = parser.parse_args()

    try:
        results = process(args)
    except Exception as e:
        print(json.dumps({"status": "error", "message": str(e)}))
        sys.exit(2)

    print(json.dumps(results, indent=2))
    sys.exit(0)


if __name__ == "__main__":
    main()
