#!/usr/bin/env python3
"""
Convert SWMM outfall discharge to CaMa-Flood lateral inflow.

Aggregates SWMM outfall discharge from the binary output file and writes
it as a CaMa-Flood lateral inflow NetCDF file. This enables feedback coupling
where urban drainage outflows enter the river/floodplain system.

SWMM outfall discharge is typically in m^3/s (CMS units). CaMa-Flood lateral
inflow is specified as runoff depth (mm/day) on a grid cell, or as direct
discharge injection at a specific grid cell.

This tool produces a NetCDF file compatible with CaMa-Flood's lateral inflow
mechanism (LROSPLIT format).

Inputs:
  - SWMM .out binary file
  - Outfall IDs to aggregate
  - Target CaMa-Flood grid cell (ix, iy)

Outputs:
  - NetCDF file with daily lateral inflow for CaMa-Flood
"""

import argparse
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np


def extract_outfall_discharge(out_path, outfall_ids):
    """
    Extract outfall discharge from SWMM .out binary or from .rpt.

    Returns: list of (datetime, total_discharge_m3s)
    """
    # Try pyswmm first
    try:
        from pyswmm import Output
        with Output(str(out_path)) as out:
            timeseries = []
            for oid in outfall_ids:
                try:
                    ts = out.node_series(oid, "total_inflow")
                    if not timeseries:
                        timeseries = [(dt, val) for dt, val in ts.items()]
                    else:
                        for i, (dt, val) in enumerate(ts.items()):
                            if i < len(timeseries):
                                timeseries[i] = (timeseries[i][0],
                                                 timeseries[i][1] + val)
                except Exception as e:
                    print(f"  WARNING: Cannot extract {oid}: {e}", file=sys.stderr)
            return timeseries
    except ImportError:
        pass

    # Fallback: parse .rpt for summary (less detailed)
    rpt_path = Path(out_path).with_suffix(".rpt")
    if rpt_path.exists():
        print("  WARNING: Using .rpt summary (no sub-daily resolution)",
              file=sys.stderr)
        # Parse outfall loading from .rpt
        # This gives totals, not timeseries — return placeholder
        return []

    return []


def aggregate_to_daily(timeseries):
    """Aggregate sub-daily timeseries to daily means."""
    daily = {}
    for dt, q in timeseries:
        date = dt.replace(hour=0, minute=0, second=0, microsecond=0)
        if date not in daily:
            daily[date] = []
        daily[date].append(q)

    daily_mean = {}
    for date, values in sorted(daily.items()):
        daily_mean[date] = np.mean(values)

    return daily_mean


def write_cama_lateral_nc(daily_q, grid_ix, grid_iy, output_path,
                          nx=None, ny=None, start_date=None):
    """
    Write CaMa-Flood lateral inflow NetCDF.

    Creates a minimal grid with the discharge concentrated at (grid_ix, grid_iy).
    """
    try:
        import netCDF4 as nc
    except ImportError:
        print("ERROR: netCDF4 required. Install with: pip install netCDF4",
              file=sys.stderr)
        sys.exit(1)

    dates = sorted(daily_q.keys())
    n_time = len(dates)

    # Default grid size (just needs to contain the target cell)
    if nx is None:
        nx = grid_ix + 2
    if ny is None:
        ny = grid_iy + 2

    ds = nc.Dataset(output_path, "w", format="NETCDF4")

    # Dimensions
    ds.createDimension("time", n_time)
    ds.createDimension("y", ny)
    ds.createDimension("x", nx)

    # Time variable
    time_var = ds.createVariable("time", "f8", ("time",))
    time_var.units = f"days since {dates[0].strftime('%Y-%m-%d')}"
    time_var.calendar = "standard"
    time_var[:] = [(d - dates[0]).days for d in dates]

    # Lateral inflow variable (m^3/s)
    lateral = ds.createVariable("lateral_inflow", "f4", ("time", "y", "x"),
                                fill_value=-9999.0)
    lateral.units = "m3/s"
    lateral.long_name = "Lateral inflow from SWMM urban drainage"
    lateral.description = "SWMM outfall discharge injected into CaMa-Flood grid"

    # Fill with zeros, then set target cell
    data = np.zeros((n_time, ny, nx), dtype=np.float32)
    for i, date in enumerate(dates):
        data[i, grid_iy, grid_ix] = daily_q[date]
    lateral[:] = data

    # Global attributes
    ds.title = "SWMM-to-CaMa-Flood lateral inflow"
    ds.source = "Generated by convert_swmm_outflow_to_cama_lateral.py"
    ds.history = f"Created {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    ds.target_cell = f"ix={grid_ix}, iy={grid_iy}"

    ds.close()
    return n_time


def main():
    parser = argparse.ArgumentParser(
        description="Convert SWMM outfall discharge to CaMa-Flood lateral inflow"
    )
    parser.add_argument("--swmm_out", required=True,
                        help="SWMM binary output file (.out)")
    parser.add_argument("--outfall_ids", required=True,
                        help='Outfall IDs to aggregate (comma-separated, e.g. "OUT1,OUT2")')
    parser.add_argument("--cama_grid_ix", type=int, required=True,
                        help="CaMa-Flood target grid cell x-index")
    parser.add_argument("--cama_grid_iy", type=int, required=True,
                        help="CaMa-Flood target grid cell y-index")
    parser.add_argument("--output", required=True,
                        help="Output NetCDF file path")
    parser.add_argument("--grid_nx", type=int, default=None,
                        help="CaMa grid x-dimension (default: auto)")
    parser.add_argument("--grid_ny", type=int, default=None,
                        help="CaMa grid y-dimension (default: auto)")
    args = parser.parse_args()

    if not os.path.isfile(args.swmm_out):
        print(f"ERROR: File not found: {args.swmm_out}", file=sys.stderr)
        sys.exit(1)

    outfall_ids = [oid.strip() for oid in args.outfall_ids.split(",")]

    print(f"Converting SWMM outfall discharge to CaMa-Flood lateral inflow")
    print(f"  SWMM output: {args.swmm_out}")
    print(f"  Outfall IDs: {outfall_ids}")
    print(f"  Target CaMa cell: ({args.cama_grid_ix}, {args.cama_grid_iy})")

    # Extract discharge timeseries
    timeseries = extract_outfall_discharge(args.swmm_out, outfall_ids)

    if not timeseries:
        print("\nWARNING: No timeseries extracted from .out file.", file=sys.stderr)
        print("This may be because pyswmm is not installed or the .out file is empty.",
              file=sys.stderr)
        print("Creating a placeholder NetCDF with zero lateral inflow...", file=sys.stderr)

        # Create placeholder with one year of zeros
        daily_q = {}
        start = datetime(2000, 1, 1)
        for i in range(365):
            daily_q[start + timedelta(days=i)] = 0.0
    else:
        # Aggregate to daily
        daily_q = aggregate_to_daily(timeseries)
        q_values = list(daily_q.values())
        print(f"\n  Daily discharge statistics:")
        print(f"    Mean: {np.mean(q_values):.4f} m^3/s")
        print(f"    Max:  {np.max(q_values):.4f} m^3/s")
        print(f"    Days: {len(daily_q)}")

    # Write NetCDF
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    n_written = write_cama_lateral_nc(daily_q, args.cama_grid_ix, args.cama_grid_iy,
                                       str(output_path), args.grid_nx, args.grid_ny)

    print(f"\nNetCDF written: {output_path}")
    print(f"  {n_written} daily timesteps")


if __name__ == "__main__":
    main()
