#!/usr/bin/env python3
"""
Generate a GSFLOW control file from configuration parameters.

Usage:
    python build_control_file.py \
        --output /path/to/gsflow.control \
        --mode GSFLOW5 \
        --start-date 1980-10-01 \
        --end-date 1990-09-30 \
        --data-file ./input/prms/basin.data \
        --param-files prms.params,gsflow.params,gvr.params \
        --modflow-name ./input/modflow/model.nam \
        --temp-module climate_hru \
        --precip-module climate_hru \
        --output-vars basin_cfs,basin_ppt,basin_actet

Pipeline Stage: s0 (Configuration)
Follows: validate → process → validate pattern
"""

import os
import sys
import argparse
from datetime import datetime


# Default module selections for different use cases
MODULE_PRESETS = {
    "gridded_forcing": {
        "temp_module": "climate_hru",
        "precip_module": "climate_hru",
        "solrad_module": "climate_hru",
        "et_module": "climate_hru",
    },
    "station_data": {
        "temp_module": "temp_1sta_laps",
        "precip_module": "precip_1sta_laps",
        "solrad_module": "ddsolrad",
        "et_module": "potet_jh",
    },
    "multi_station": {
        "temp_module": "temp_dist2",
        "precip_module": "precip_dist2",
        "solrad_module": "ddsolrad",
        "et_module": "potet_jh",
    },
}

# Common GSFLOW output variables
COMMON_OUTPUT_VARS = [
    "basin_cfs", "basin_ppt", "basin_tmax", "basin_tmin",
    "basin_potet", "basin_actet", "basin_sroff", "basin_ssflow",
    "basin_gwflow", "basin_stflow", "basin_soil_moist",
    "basin_recharge", "basin_snow",
]


def validate_inputs(args):
    """Validate control file generation parameters."""
    errors = []

    if args.mode not in ("GSFLOW5", "PRMS5", "MODFLOW"):
        errors.append(f"Invalid mode: {args.mode}. Must be GSFLOW5, PRMS5, or MODFLOW.")

    try:
        start = datetime.strptime(args.start_date, "%Y-%m-%d")
        end = datetime.strptime(args.end_date, "%Y-%m-%d")
        if start >= end:
            errors.append("start_date must be before end_date")
    except ValueError as e:
        errors.append(f"Invalid date format: {e}. Use YYYY-MM-DD.")

    if args.mode in ("GSFLOW5", "PRMS5"):
        if not args.data_file and not args.day_files:
            errors.append("Must specify --data-file or --day-files for PRMS/GSFLOW mode")
        if not args.param_files:
            errors.append("Must specify --param-files for PRMS/GSFLOW mode")

    if args.mode in ("GSFLOW5", "MODFLOW"):
        if not args.modflow_name:
            errors.append("Must specify --modflow-name for GSFLOW/MODFLOW mode")

    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return False
    return True


def write_control_param(f, name, values, dtype):
    """
    Write a single control file parameter block.

    Args:
        f: file handle
        name: parameter name
        values: list of values
        dtype: data type (1=int, 2=float, 4=string)
    """
    f.write("####\n")
    f.write(f"{name}\n")
    f.write(f"{len(values)}\n")
    f.write(f"{dtype}\n")
    for v in values:
        f.write(f"{v}\n")


def generate_control_file(output_path, config):
    """
    Generate a complete GSFLOW control file.

    Args:
        output_path: path to write control file
        config: dict with all configuration parameters
    """
    start = datetime.strptime(config["start_date"], "%Y-%m-%d")
    end = datetime.strptime(config["end_date"], "%Y-%m-%d")

    with open(output_path, "w") as f:
        f.write(f"GSFLOW control file generated by build_control_file.py\n")

        # Model mode
        write_control_param(f, "model_mode", [config["mode"]], 4)

        # Time period
        write_control_param(f, "start_time", [
            start.year, start.month, start.day, 0, 0, 0
        ], 1)
        write_control_param(f, "end_time", [
            end.year, end.month, end.day, 0, 0, 0
        ], 1)

        # MODFLOW time zero (day before start)
        if config["mode"] in ("GSFLOW5", "MODFLOW"):
            from datetime import timedelta
            mf_zero = start - timedelta(days=1)
            write_control_param(f, "modflow_time_zero", [
                mf_zero.year, mf_zero.month, mf_zero.day, 0, 0, 0
            ], 1)

        # Data file
        if config.get("data_file"):
            write_control_param(f, "data_file", [config["data_file"]], 4)

        # Parameter files
        if config.get("param_files"):
            write_control_param(f, "param_file", config["param_files"], 4)

        # MODFLOW name file
        if config.get("modflow_name"):
            write_control_param(f, "modflow_name", [config["modflow_name"]], 4)

        # Climate modules
        modules = config.get("modules", {})
        for mod_name in ["temp_module", "precip_module", "solrad_module", "et_module",
                         "srunoff_module", "strmflow_module", "soilzone_module"]:
            if mod_name in modules:
                write_control_param(f, mod_name, [modules[mod_name]], 4)

        # Pre-processed climate day files
        if config.get("day_files"):
            day_map = {
                "tmax": "tmax_day", "tmin": "tmin_day",
                "precip": "precip_day", "swrad": "swrad_day",
                "potet": "potet_day"
            }
            for var, param in day_map.items():
                for df in config["day_files"]:
                    if var in df:
                        write_control_param(f, param, [df], 4)

        # Output files
        if config.get("output_file"):
            write_control_param(f, "model_output_file", [config["output_file"]], 4)
        if config.get("gsflow_output"):
            write_control_param(f, "gsflow_output_file", [config["gsflow_output"]], 4)
        if config.get("csv_output"):
            write_control_param(f, "csv_output_file", [config["csv_output"]], 4)

        # Basin output control
        output_vars = config.get("output_vars", COMMON_OUTPUT_VARS)
        if output_vars:
            write_control_param(f, "basinOutON_OFF", [1], 1)
            write_control_param(f, "basinOutVars", [len(output_vars)], 1)
            write_control_param(f, "basinOutVar_names", output_vars, 4)
            write_control_param(f, "basinOut_freq", [config.get("output_freq", 1)], 1)

        # Debug and validation flags
        write_control_param(f, "print_debug", [config.get("print_debug", 0)], 1)
        write_control_param(f, "parameter_check_flag", [config.get("param_check", 1)], 1)

        # Unit settings
        if "temp_units" in config:
            write_control_param(f, "temp_units", [config["temp_units"]], 1)
        if "precip_units" in config:
            write_control_param(f, "precip_units", [config["precip_units"]], 1)

        f.write("####\n")

    print(f"  Control file written to {output_path}")


def validate_outputs(output_path, config):
    """Validate the generated control file."""
    errors = []

    if not os.path.isfile(output_path):
        errors.append(f"Control file not created: {output_path}")
        return False

    with open(output_path) as f:
        content = f.read()

    # Check required parameters exist
    required = ["model_mode", "start_time", "end_time"]
    if config["mode"] in ("GSFLOW5", "PRMS5"):
        required.extend(["param_file"])
    if config["mode"] in ("GSFLOW5", "MODFLOW"):
        required.extend(["modflow_name", "modflow_time_zero"])

    for param in required:
        if param not in content:
            errors.append(f"Missing required parameter: {param}")

    # Check delimiter count (should have matching ####)
    delimiters = content.count("####")
    if delimiters < 5:
        errors.append(f"Too few #### delimiters ({delimiters}). File may be malformed.")

    if errors:
        for e in errors:
            print(f"WARNING: {e}", file=sys.stderr)
        return False

    print("  Control file validation PASSED")
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate GSFLOW control file")
    parser.add_argument("--output", required=True, help="Output control file path")
    parser.add_argument("--mode", default="GSFLOW5", choices=["GSFLOW5", "PRMS5", "MODFLOW"])
    parser.add_argument("--start-date", required=True, help="Start date YYYY-MM-DD")
    parser.add_argument("--end-date", required=True, help="End date YYYY-MM-DD")
    parser.add_argument("--data-file", help="PRMS data file path")
    parser.add_argument("--param-files", help="Comma-separated parameter file paths")
    parser.add_argument("--modflow-name", help="MODFLOW name file path")
    parser.add_argument("--day-files", help="Comma-separated .day file paths")
    parser.add_argument("--temp-module", default="climate_hru")
    parser.add_argument("--precip-module", default="climate_hru")
    parser.add_argument("--solrad-module", default="climate_hru")
    parser.add_argument("--et-module", default="potet_jh")
    parser.add_argument("--srunoff-module", default="srunoff_smidx")
    parser.add_argument("--strmflow-module", default="strmflow")
    parser.add_argument("--output-vars", help="Comma-separated output variable names")
    parser.add_argument("--print-debug", type=int, default=0)
    args = parser.parse_args()

    print("=" * 60)
    print("GSFLOW Control File Generator")
    print("=" * 60)

    # ── Step 1: Validate ──
    if not validate_inputs(args):
        sys.exit(1)

    # ── Step 2: Build config ──
    config = {
        "mode": args.mode,
        "start_date": args.start_date,
        "end_date": args.end_date,
        "data_file": args.data_file,
        "param_files": args.param_files.split(",") if args.param_files else [],
        "modflow_name": args.modflow_name,
        "day_files": args.day_files.split(",") if args.day_files else [],
        "modules": {
            "temp_module": args.temp_module,
            "precip_module": args.precip_module,
            "solrad_module": args.solrad_module,
            "et_module": args.et_module,
            "srunoff_module": args.srunoff_module,
            "strmflow_module": args.strmflow_module,
        },
        "output_vars": args.output_vars.split(",") if args.output_vars else COMMON_OUTPUT_VARS,
        "print_debug": args.print_debug,
        "param_check": 1,
    }

    # ── Step 3: Generate ──
    print(f"\nGenerating control file: {args.output}")
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    generate_control_file(args.output, config)

    # ── Step 4: Validate ──
    validate_outputs(args.output, config)

    print(f"\nDone! Control file → {args.output}")


if __name__ == "__main__":
    main()
