"""Exact-source GSFLOW CLI help/version exits before model initialization."""
from pathlib import Path
import hashlib,sys
root=Path(sys.argv[1]).resolve();workspace=Path.cwd().resolve()
if root!=workspace and workspace not in root.parents:raise SystemExit('Source outside working directory')
p=root/'GSFLOW/src/gsflow/gsflow_fortran.f90';raw=p.read_bytes();digest=hashlib.sha256(raw).hexdigest()
EXPECTED='394f6a9b5678bb8b2622b782c9ebc94e54316036ee5cd32dc225fc8ddb951385'
PATCHED='8efa248523e0f9081f3c6b7c08ce8f10f6692dbb80e0068eede2e9ef587584bd'
NEW="      PROGRAM GSFLOW_FORTRAN\n!***********************************************************************\n! PRMS main that controls time loop\n!***********************************************************************\n      USE PRMS_CONSTANTS, ONLY: RUN, DECL, INIT, CLEAN, SETDIMENS\n      USE PRMS_MODULE, ONLY: Number_timesteps, GSFLOW_versn\n      USE PRMS_DLL, ONLY: gsflow_prms\n      IMPLICIT NONE\n! Local Variables\n      INTEGER :: i\n      CHARACTER(LEN=128) :: cli_arg\n      LOGICAL :: AFR, MS_GSF_converge\n      INTEGER :: Nsegshold, Nlakeshold\n      INTEGER, ALLOCATABLE :: Idivert(:)\n      DOUBLE PRECISION, ALLOCATABLE :: Diversions(:), LAKEVOL(:), LAKEVAP(:)\n      DOUBLE PRECISION, ALLOCATABLE :: agDemand(:), DELTAVOL(:), EXCHANGE(:)\n!***********************************************************************\n      ! CLI-only startup exit before reading any scientific inputs.\n      IF ( COMMAND_ARGUMENT_COUNT() == 1 ) THEN\n        CALL GET_COMMAND_ARGUMENT(1, cli_arg)\n        IF ( TRIM(cli_arg) == '--version' ) THEN\n          PRINT '(2A)', 'GSFLOW ', GSFLOW_versn\n          STOP\n        ELSE IF ( TRIM(cli_arg) == '--help' .OR. TRIM(cli_arg) == '-h' ) THEN\n          PRINT '(2A)', 'GSFLOW ', GSFLOW_versn\n          PRINT '(A)', 'Usage: gsflow CONTROL_FILE [control arguments]'\n          STOP\n        ENDIF\n      ENDIF\n      AFR = .TRUE.\n      MS_GSF_converge = .FALSE.\n      Nlakeshold = 1\n      Nsegshold = 1\n      ALLOCATE ( Idivert(Nlakeshold), DELTAVOL(Nlakeshold),LAKEVOL(Nlakeshold), LAKEVAP(Nlakeshold)  )\n      ALLOCATE ( Diversions(Nsegshold), agDemand(Nsegshold), EXCHANGE(Nsegshold) )\n      Diversions = 0.0D0\n      agDemand = 0.0D0\n      EXCHANGE = 0.0D0\n      LAKEVOL = 0.0D0\n      LAKEVAP = 0.0D0\n      DELTAVOL = 0.0D0\n      CALL gsflow_prms(SETDIMENS, AFR, MS_GSF_converge, Nsegshold, Nlakeshold, &\n     &                 Diversions, Idivert, EXCHANGE, DELTAVOL, LAKEVOL, LAKEVAP, agDemand)\n\n      CALL gsflow_prms(DECL, AFR, MS_GSF_converge, Nsegshold, Nlakeshold, &\n     &                 Diversions, Idivert, EXCHANGE, DELTAVOL, LAKEVOL, LAKEVAP, agDemand)\n\n      CALL gsflow_prms(INIT, AFR, MS_GSF_converge, Nsegshold, Nlakeshold, &\n     &                 Diversions, Idivert, EXCHANGE, DELTAVOL, LAKEVOL, LAKEVAP, agDemand)\n      DO i = 1, Number_timesteps\n        CALL gsflow_prms(RUN, AFR, MS_GSF_converge, Nsegshold, Nlakeshold, &\n     &                   Diversions, Idivert, EXCHANGE, DELTAVOL, LAKEVOL, LAKEVAP, agDemand)\n      ENDDO\n      CALL gsflow_prms(CLEAN, AFR, MS_GSF_converge, Nsegshold, Nlakeshold, &\n     &                 Diversions, Idivert, EXCHANGE, DELTAVOL, LAKEVOL, LAKEVAP, agDemand)\n\n      END PROGRAM GSFLOW_FORTRAN\n"
if digest==PATCHED:print('GSFLOW CLI patch already applied')
elif digest!=EXPECTED:raise SystemExit('Unexpected GSFLOW source')
else:
 p.write_text(NEW)
 print('Applied genuine source CLI exits')
