#!/usr/bin/env python3
"""
Create SWMM rainfall timeseries from CSV gauge data.

Reads rainfall data from a CSV file (timestamp + value) and converts it to
SWMM-compatible timeseries format. Handles unit conversion between:
  - intensity (mm/hr) — SWMM native for INTENSITY format
  - accumulated depth (mm) per timestep — converted to intensity

Output format is SWMM DAT timeseries (tab-separated: MM/DD/YYYY HH:MM:SS value).

Inputs:
  - Rain gauge CSV with columns: datetime (or date+time), value
  - Format specification: intensity_mm_hr or depth_mm
  - Timestep in minutes

Outputs:
  - SWMM timeseries file (.dat)
"""

import argparse
import csv
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path


def parse_datetime(dt_str):
    """Try multiple datetime formats."""
    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M",
        "%Y/%m/%d %H:%M:%S",
        "%Y/%m/%d %H:%M",
        "%m/%d/%Y %H:%M:%S",
        "%m/%d/%Y %H:%M",
        "%d/%m/%Y %H:%M:%S",
        "%Y%m%d%H%M",
    ]
    for fmt in formats:
        try:
            return datetime.strptime(dt_str.strip(), fmt)
        except ValueError:
            continue
    raise ValueError(f"Cannot parse datetime: '{dt_str}'")


def read_rain_csv(csv_path, value_col=None):
    """Read rainfall data from CSV."""
    records = []
    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames

        # Auto-detect datetime column
        dt_col = None
        for c in cols:
            if c.lower() in ("datetime", "date_time", "timestamp", "time", "date"):
                dt_col = c
                break
        if dt_col is None:
            dt_col = cols[0]

        # Auto-detect value column
        if value_col is None:
            for c in cols:
                if c.lower() in ("value", "rain", "rainfall", "precip",
                                  "precipitation", "intensity", "depth"):
                    value_col = c
                    break
            if value_col is None:
                value_col = cols[1] if len(cols) > 1 else cols[0]

        for row in reader:
            try:
                dt = parse_datetime(row[dt_col])
                val = float(row[value_col])
                records.append((dt, val))
            except (ValueError, KeyError) as e:
                print(f"WARNING: Skipping row: {e}", file=sys.stderr)
                continue

    records.sort(key=lambda x: x[0])
    return records


def convert_depth_to_intensity(records, timestep_min):
    """Convert accumulated depth (mm) per timestep to intensity (mm/hr)."""
    converted = []
    for dt, depth_mm in records:
        intensity = depth_mm / (timestep_min / 60.0)
        converted.append((dt, round(intensity, 4)))
    return converted


def write_swmm_timeseries(records, output_path, series_name="RainGage1"):
    """Write SWMM timeseries format."""
    with open(output_path, "w") as f:
        f.write(f";;SWMM Rainfall Timeseries: {series_name}\n")
        f.write(";;Generated by create_rain_timeseries.py\n")
        f.write(";;\n")
        for dt, value in records:
            if value > 0:  # Only write non-zero values
                date_str = dt.strftime("%m/%d/%Y")
                time_str = dt.strftime("%H:%M:%S")
                f.write(f"{series_name}\t{date_str}\t{time_str}\t{value:.4f}\n")
    return len([r for r in records if r[1] > 0])


def main():
    parser = argparse.ArgumentParser(
        description="Create SWMM rainfall timeseries from CSV gauge data"
    )
    parser.add_argument("--rain_csv", required=True,
                        help="Input rainfall CSV file")
    parser.add_argument("--format", dest="rain_format", required=True,
                        choices=["intensity_mm_hr", "depth_mm"],
                        help="Input data format: intensity (mm/hr) or depth (mm per timestep)")
    parser.add_argument("--timestep_min", type=float, default=5,
                        help="Timestep in minutes (default: 5)")
    parser.add_argument("--output", required=True,
                        help="Output SWMM timeseries file (.dat)")
    parser.add_argument("--series_name", default="RainGage1",
                        help="Timeseries name in SWMM (default: RainGage1)")
    parser.add_argument("--value_col", default=None,
                        help="Column name for rainfall values (auto-detected if omitted)")
    args = parser.parse_args()

    if not os.path.isfile(args.rain_csv):
        print(f"ERROR: File not found: {args.rain_csv}", file=sys.stderr)
        sys.exit(1)

    print(f"Reading rainfall data from {args.rain_csv}...")
    records = read_rain_csv(args.rain_csv, args.value_col)
    print(f"  Read {len(records)} records")

    if not records:
        print("ERROR: No valid records found", file=sys.stderr)
        sys.exit(1)

    # Convert units if needed
    if args.rain_format == "depth_mm":
        print(f"  Converting depth (mm/{args.timestep_min}min) to intensity (mm/hr)...")
        records = convert_depth_to_intensity(records, args.timestep_min)

    # Statistics
    values = [r[1] for r in records]
    nonzero = [v for v in values if v > 0]
    print(f"  Period: {records[0][0]} to {records[-1][0]}")
    print(f"  Max intensity: {max(values):.2f} mm/hr")
    print(f"  Non-zero records: {len(nonzero)} / {len(records)}")
    if nonzero:
        print(f"  Mean non-zero intensity: {sum(nonzero)/len(nonzero):.2f} mm/hr")

    # Write output
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    n_written = write_swmm_timeseries(records, output_path, args.series_name)

    print(f"\nTimeseries written: {output_path}")
    print(f"  {n_written} non-zero entries written")


if __name__ == "__main__":
    main()
