#!/usr/bin/env python3
"""
Generate HYPE info.txt configuration file.

Assembles the main control file with simulation dates, directories,
output variables, model options, and optional criteria.

Usage:
    python configure_info.py \
        --start 2005-01-01 --end 2010-12-31 \
        --warmup_years 1 \
        --modeldir ./modelfiles/ \
        --forcingdir ./forcingdir/ \
        --resultdir ./resultdir/ \
        --output info.txt \
        --petmodel 1 \
        --substances none
"""

import argparse
import sys
import os
from datetime import datetime, timedelta


def generate_info_txt(start_date, end_date, warmup_years,
                      modeldir, forcingdir, resultdir, logdir,
                      output_path, petmodel=1, substances='none',
                      output_vars=None):
    """Generate HYPE info.txt configuration file."""

    # Parse dates
    bdate = datetime.strptime(start_date, '%Y-%m-%d')
    edate = datetime.strptime(end_date, '%Y-%m-%d')

    # Criteria/output start date (after warmup)
    cdate = bdate + timedelta(days=warmup_years * 365)
    if cdate >= edate:
        cdate = bdate  # No warmup if period too short

    # Default output variables
    if output_vars is None:
        output_vars = ['cout', 'rout', 'snow', 'evap', 'cprc', 'soim']

    # Ensure trailing slashes on directories
    for d in [modeldir, forcingdir, resultdir, logdir]:
        if not d.endswith('/'):
            d += '/'

    # Write info.txt
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)

    with open(output_path, 'w') as f:
        f.write("!! info.txt generated by HydroCraft HYPE tools\n")
        f.write("!!\n")

        # Simulation period
        f.write(f"bdate\t{bdate.strftime('%Y-%m-%d')}\n")
        f.write(f"cdate\t{cdate.strftime('%Y-%m-%d')}\n")
        f.write(f"edate\t{edate.strftime('%Y-%m-%d')}\n")

        # Directories — CRITICAL: must end with /
        f.write(f"resultdir\t{resultdir}\n")
        f.write(f"modeldir\t{modeldir}\n")
        f.write(f"forcingdir\t{forcingdir}\n")
        f.write(f"logdir\t{logdir}\n")
        f.write("!!\n")

        # Substances
        if substances and substances != 'none':
            f.write(f"substance\t{substances}\n")
            f.write("!!\n")

        # Output configuration
        f.write("!! Time series output\n")
        f.write(f"timeoutput variable\t" + "\t".join(output_vars) + "\n")
        f.write("timeoutput meanperiod\t1\n")
        f.write("timeoutput decimals\t3\n")
        f.write("!!\n")

        # Map output (monthly averages)
        f.write("!! Map output (monthly)\n")
        map_vars = [v for v in output_vars if v not in ['rout']]
        f.write(f"mapoutput variable\t" + "\t".join(map_vars) + "\n")
        f.write("mapoutput meanperiod\t3\n")
        f.write("mapoutput decimals\t3\n")
        f.write("!!\n")

        # Model options
        f.write("!! Model options\n")
        f.write(f"modeloption petmodel\t{petmodel}\n")
        f.write("modeloption snowfallmodel\t0\n")
        f.write("modeloption snowmeltmodel\t2\n")

    print(f"Generated info.txt: {output_path}")
    print(f"  Period: {bdate.strftime('%Y-%m-%d')} to {edate.strftime('%Y-%m-%d')}")
    print(f"  Warmup: {warmup_years} year(s), output starts {cdate.strftime('%Y-%m-%d')}")
    print(f"  PET model: {petmodel}")
    print(f"  Output vars: {', '.join(output_vars)}")


def main():
    parser = argparse.ArgumentParser(description='Generate HYPE info.txt')
    parser.add_argument('--start', required=True, help='Start date (YYYY-MM-DD)')
    parser.add_argument('--end', required=True, help='End date (YYYY-MM-DD)')
    parser.add_argument('--warmup_years', type=int, default=1, help='Warmup period in years')
    parser.add_argument('--modeldir', default='./modelfiles/', help='Model files directory')
    parser.add_argument('--forcingdir', default='./forcingdir/', help='Forcing data directory')
    parser.add_argument('--resultdir', default='./resultdir/', help='Result output directory')
    parser.add_argument('--logdir', default='./logdir/', help='Log directory')
    parser.add_argument('--output', default='info.txt', help='Output info.txt path')
    parser.add_argument('--petmodel', type=int, default=1,
                       help='PET model: 0=default, 1=Jensen-Haise, 2=Hargreaves, 5=Penman-Monteith')
    parser.add_argument('--substances', default='none',
                       help='Substances to simulate: "none", "N", "P", "N P"')

    args = parser.parse_args()

    generate_info_txt(
        args.start, args.end, args.warmup_years,
        args.modeldir, args.forcingdir, args.resultdir, args.logdir,
        args.output, args.petmodel, args.substances
    )


if __name__ == '__main__':
    main()
