#!/usr/bin/env python3
"""
Configure CLM (Community Land Model) coupling for ParFlow.

Generates:
- drv_clmin.dat: CLM driver configuration (timestep, output, options)
- drv_vegm.dat: Vegetation type map (IGBP class per grid cell)
- drv_vegp.dat: Vegetation parameter file (LAI, SAI, z0 per PFT)

CLM provides the land surface boundary condition for ParFlow:
evapotranspiration, snow, canopy interception, radiation balance.

Usage:
    python setup_clm_driver.py \
        --domain_json outputs/parflow_run/domain/domain_definition.json \
        --surface_mask_npy outputs/parflow_run/domain/surface_mask.npy \
        --start_date 2000-01-01 --end_date 2010-12-31 \
        --output_dir outputs/parflow_run/clm/

Author: Jianyun Zhang Research Group, Hohai University
"""

import argparse
import json
import os
import sys
from datetime import datetime

import numpy as np

try:
    import rasterio
    from pyproj import Transformer
except ImportError as e:
    print(json.dumps({"status": "error", "message": f"Missing dependency: {e}"}))
    sys.exit(1)


HYDROCRAFT_ROOT = "KISSPATH_ROOT"
AVHRR_PATH = os.path.join(HYDROCRAFT_ROOT, "data/forcing/AVHRR")

# AVHRR -> IGBP mapping for CLM
AVHRR_TO_IGBP = {
    0: 17,   # Water -> Water Bodies
    1: 1,    # Evergreen Needleleaf -> ENF
    2: 2,    # Evergreen Broadleaf -> EBF
    3: 3,    # Deciduous Needleleaf -> DNF
    4: 4,    # Deciduous Broadleaf -> DBF
    5: 5,    # Mixed Forest
    6: 6,    # Closed Shrublands
    7: 7,    # Open Shrublands
    8: 8,    # Woody Savannas
    9: 9,    # Savannas
    10: 10,  # Grasslands
    11: 11,  # Permanent Wetlands
    12: 12,  # Croplands
    13: 13,  # Urban
    14: 14,  # Cropland/Natural Mosaic
    15: 15,  # Snow and Ice
    16: 16,  # Barren
}

# CLM vegetation parameters by IGBP type
# (z_top, z_bot, LAI_max, SAI, d/h, z0/h)
CLM_VEG_PARAMS = {
    1:  (17.0, 8.5, 5.0, 1.0, 0.67, 0.10),   # ENF
    2:  (35.0, 1.0, 6.0, 2.0, 0.67, 0.10),   # EBF
    3:  (14.0, 7.0, 4.0, 0.5, 0.67, 0.10),   # DNF
    4:  (20.0, 11.5, 5.0, 0.5, 0.67, 0.10),  # DBF
    5:  (20.0, 8.5, 5.0, 1.0, 0.67, 0.10),   # Mixed
    6:  (0.5, 0.1, 2.0, 0.5, 0.67, 0.10),    # Closed Shrub
    7:  (0.5, 0.1, 1.5, 0.5, 0.67, 0.10),    # Open Shrub
    8:  (15.0, 3.0, 3.0, 0.5, 0.67, 0.10),   # Woody Savanna
    9:  (2.0, 0.5, 2.5, 0.5, 0.67, 0.10),    # Savanna
    10: (0.5, 0.1, 2.5, 0.5, 0.67, 0.10),    # Grassland
    11: (0.5, 0.1, 3.0, 0.5, 0.67, 0.10),    # Wetland
    12: (0.5, 0.1, 4.0, 0.5, 0.67, 0.10),    # Cropland
    13: (0.5, 0.1, 0.5, 0.5, 0.67, 0.10),    # Urban
    14: (0.5, 0.1, 3.0, 0.5, 0.67, 0.10),    # Crop/Natural
    15: (0.0, 0.0, 0.0, 0.0, 0.00, 0.00),    # Snow/Ice
    16: (0.0, 0.0, 0.5, 0.0, 0.00, 0.00),    # Barren
    17: (0.0, 0.0, 0.0, 0.0, 0.00, 0.00),    # Water
}


def generate_drv_clmin(output_dir, nx, ny, dt_seconds, start_date, end_date,
                       run_name, met_prefix):
    """Generate drv_clmin.dat CLM driver configuration."""
    start_dt = datetime.strptime(start_date, "%Y-%m-%d")
    end_dt = datetime.strptime(end_date, "%Y-%m-%d")

    lines = [
        "!=========================================================================",
        "! CLM Driver Input File (drv_clmin.dat)",
        "! Generated by HydroCraft ParFlow KI",
        "!=========================================================================",
        "",
        "!--- Simulation timing ---",
        f"startcode         2        ! 1=restart, 2=initial",
        f"clm_ic            2        ! 1=restart, 2=defined initial",
        f"maession          1        ! 1 for coupled run",
        f"mession           1",
        f"nz                1        ! Number of soil layers in CLM output",
        "",
        "!--- Grid dimensions (must match ParFlow) ---",
        f"clm_nx            {nx}",
        f"clm_ny            {ny}",
        "",
        "!--- Timestep ---",
        f"ts                {dt_seconds}      ! Timestep in seconds",
        "",
        "!--- Dates ---",
        f"syr               {start_dt.year}",
        f"smo               {start_dt.month}",
        f"sda               {start_dt.day}",
        f"shr               0",
        f"smn               0",
        f"sss               0",
        "",
        f"eyr               {end_dt.year}",
        f"emo               {end_dt.month}",
        f"eda               {end_dt.day}",
        f"ehr               0",
        f"emn               0",
        f"ess               0",
        "",
        "!--- Meteorological forcing ---",
        f"metf1d            '{met_prefix}'",
        f"metpath           './'",
        "",
        "!--- Vegetation data ---",
        f"vegp              'drv_vegp.dat'",
        f"vegm              'drv_vegm.dat'",
        "",
        "!--- Output ---",
        f"outf1d            '{run_name}'",
        f"clm_odir          './'",
        "",
        "!--- CLM options ---",
        "clm_dump          0",
        "maession          1",
        "",
    ]

    path = os.path.join(output_dir, "drv_clmin.dat")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path


def generate_drv_vegm(output_dir, nx, ny, vegtype_map, mask_2d, lat_map, lon_map):
    """Generate drv_vegm.dat vegetation type map."""
    path = os.path.join(output_dir, "drv_vegm.dat")
    with open(path, "w") as f:
        f.write("x y lat lon sand clay color fractional coverage\n")
        f.write(f"1 1 {nx} {ny}\n")
        for j in range(ny):
            for i in range(nx):
                if mask_2d[j, i] == 0:
                    vt = 17  # Water for inactive
                else:
                    vt = int(vegtype_map[j, i])
                # Write: x y lat lon sand clay color frac1 frac2 ... frac18
                lat = lat_map[j, i] if lat_map is not None else 0.0
                lon = lon_map[j, i] if lon_map is not None else 0.0
                fracs = [0.0] * 18
                if vt >= 1 and vt <= 17:
                    fracs[vt - 1] = 1.0
                frac_str = " ".join(f"{v:.2f}" for v in fracs)
                f.write(f"{i+1} {j+1} {lat:.4f} {lon:.4f} "
                        f"0.40 0.20 4 {frac_str}\n")
    return path


def generate_drv_vegp(output_dir):
    """Generate drv_vegp.dat vegetation parameter file."""
    path = os.path.join(output_dir, "drv_vegp.dat")
    with open(path, "w") as f:
        f.write("! CLM Vegetation Parameters\n")
        f.write("! IGBP type, z_top(m), z_bot(m), LAI_max, SAI, d/h, z0/h\n")
        for igbp_type in range(1, 18):
            params = CLM_VEG_PARAMS.get(igbp_type, (0, 0, 0, 0, 0, 0))
            f.write(f"{igbp_type:3d}  {params[0]:6.1f}  {params[1]:6.1f}  "
                    f"{params[2]:5.1f}  {params[3]:5.1f}  "
                    f"{params[4]:5.2f}  {params[5]:5.2f}\n")
    return path


def process(domain_json, surface_mask_npy, start_date, end_date, output_dir,
            dt_seconds=3600, run_name="parflow_run"):
    os.makedirs(output_dir, exist_ok=True)

    with open(domain_json) as f:
        domain = json.load(f)

    mask_2d = np.load(surface_mask_npy)
    grid = domain["grid"]
    nx, ny = grid["nx"], grid["ny"]
    dx, dy = grid["dx"], grid["dy"]
    origin_x = domain["origin"]["x"]
    origin_y = domain["origin"]["y"]
    utm_epsg = domain["crs"]["epsg"]

    # Build vegetation type map
    vegtype = np.full((ny, nx), 10, dtype=np.int32)  # Default: grassland

    # Try AVHRR lookup
    avhrr_file = None
    if os.path.isdir(AVHRR_PATH):
        import glob
        candidates = glob.glob(os.path.join(AVHRR_PATH, "**/*.tif"), recursive=True)
        if candidates:
            avhrr_file = candidates[0]

    lat_map = np.zeros((ny, nx))
    lon_map = np.zeros((ny, nx))
    transformer = Transformer.from_crs(
        f"EPSG:{utm_epsg}", "EPSG:4326", always_xy=True
    )

    for j in range(ny):
        for i in range(nx):
            cx = origin_x + (i + 0.5) * dx
            cy = origin_y + (j + 0.5) * dy
            lo, la = transformer.transform(cx, cy)
            lat_map[j, i] = la
            lon_map[j, i] = lo

    if avhrr_file:
        with rasterio.open(avhrr_file) as src:
            for j in range(ny):
                for i in range(nx):
                    if mask_2d[j, i] == 0:
                        continue
                    try:
                        row, col = src.index(lon_map[j, i], lat_map[j, i])
                        lc = int(src.read(1, window=rasterio.windows.Window(col, row, 1, 1))[0, 0])
                        vegtype[j, i] = AVHRR_TO_IGBP.get(lc, 10)
                    except Exception:
                        vegtype[j, i] = 10

    # Generate CLM files
    met_prefix = "NLDAS"
    clmin_path = generate_drv_clmin(output_dir, nx, ny, dt_seconds,
                                     start_date, end_date, run_name, met_prefix)
    vegm_path = generate_drv_vegm(output_dir, nx, ny, vegtype, mask_2d,
                                   lat_map, lon_map)
    vegp_path = generate_drv_vegp(output_dir)

    result = {
        "status": "success",
        "files": {
            "drv_clmin": clmin_path,
            "drv_vegm": vegm_path,
            "drv_vegp": vegp_path,
        },
        "clm_timestep_seconds": dt_seconds,
        "grid": {"nx": nx, "ny": ny},
    }
    return result


def main():
    parser = argparse.ArgumentParser(description="Setup CLM driver for ParFlow")
    parser.add_argument("--domain_json", required=True)
    parser.add_argument("--surface_mask_npy", required=True)
    parser.add_argument("--start_date", required=True, help="YYYY-MM-DD")
    parser.add_argument("--end_date", required=True, help="YYYY-MM-DD")
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--dt_seconds", type=int, default=3600)
    parser.add_argument("--run_name", default="parflow_run")
    args = parser.parse_args()

    result = process(args.domain_json, args.surface_mask_npy,
                     args.start_date, args.end_date, args.output_dir,
                     args.dt_seconds, args.run_name)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
