#!/usr/bin/env python3
"""Preflight check for Elmer_Ice — auto-generated by KDT v5.0"""
import os, sys, shutil

PASS = FAIL = 0
MODEL_NAME = "Elmer_Ice"

def check_file(path, label, executable=False):
    global PASS, FAIL
    if os.path.isfile(path):
        if executable and not os.access(path, os.X_OK):
            print(f"  WARN  {label}: exists but not executable: {path}")
            FAIL += 1
        else:
            print(f"  OK    {label}: {path}")
            PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_dir(path, label):
    global PASS, FAIL
    if os.path.isdir(path):
        print(f"  OK    {label}: {path} ({len(os.listdir(path))} items)")
        PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_import(module, label):
    # Also search HydroCraft python_env for packages
    import sys
    _penv = "KISSPATH_PYTHON_ENV/lib/python3.12/site-packages"
    if _penv not in sys.path:
        sys.path.insert(0, _penv)
    global PASS, FAIL
    try:
        __import__(module)
        print(f"  OK    {label}: import {module}")
        PASS += 1
    except ImportError as e:
        print(f"  FAIL  {label}: {e}")
        print(f"         Fix: pip install {module.split('.')[0]}")
        FAIL += 1

def main():
    global PASS, FAIL
    print(f"{' PREFLIGHT: Elmer_Ice ':=^60}")
    print()
    check_dir("KISSPATH_KI_ROOT/Elmer_Ice/knowledge_infrastructure/tools", "KI tools directory")
    # Model-specific binary/package check
    check_file("KISSPATH_BINARIES/Elmer_Ice/install/bin/ElmerSolver", "Elmer_Ice binary", executable=True)
    # Check diagnostics
    ki_dir = os.path.dirname(os.path.abspath(__file__))
    triplets = os.path.join(ki_dir, "diagnostics", "triplets.yaml")
    if os.path.isfile(triplets):
        print(f"  INFO  Diagnostics available: {triplets}")

    print(f"\n  Results: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL > 0 else 0)

if __name__ == "__main__":
    main()
