"""
MARRMoT Execution Wrapper
==========================
Run a MARRMoT model via GNU Octave subprocess. Generates an Octave script
from the forcing CSV + parameter JSON, executes it, and captures output.

CRITICAL: Requires GNU Octave with optim package installed.
  The wrapper generates a temporary .m script and runs it via `octave --eval`.

CRITICAL: delta_t must be 1 for daily data. If delta_t does not match
  the forcing timestep, all fluxes will be scaled incorrectly (dt_009).

CRITICAL: S0 vector length must equal the model's numStores. Too few
  elements cause an index error; too many are silently ignored (dt_012).

Usage:
  python run_marrmot.py --forcing forcing.csv \
    --model m_29_hymod_5p_5s \
    --params params.json \
    --output run_output.json

  python run_marrmot.py --forcing forcing.csv \
    --model m_01_collie1_1p_1s \
    --theta "[100]" --s0 "[0]" \
    --output run_output.json
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile
import re

import numpy as np


def validate_inputs(args):
    """Validate inputs before building Octave script."""
    errors = []

    if not os.path.isfile(args.forcing):
        errors.append(f"Forcing file not found: {args.forcing}")

    if args.params and not os.path.isfile(args.params):
        errors.append(f"Parameter file not found: {args.params}")

    if not args.params and not args.theta:
        errors.append("Either --params (JSON) or --theta must be provided")

    if args.marrmot_path and not os.path.isdir(args.marrmot_path):
        errors.append(f"MARRMoT path not found: {args.marrmot_path}")

    # Check Octave is available
    try:
        result = subprocess.run(["octave", "--version"],
                                capture_output=True, text=True, timeout=10)
        if result.returncode != 0:
            errors.append("Octave not found or not working")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        errors.append("GNU Octave not installed or not in PATH")

    if errors:
        print(json.dumps({"status": "error", "errors": errors}))
        sys.exit(1)


def load_params(args):
    """Load model parameters from JSON file or CLI args."""
    if args.params:
        with open(args.params) as f:
            pdata = json.load(f)
        theta = pdata.get("theta", [])
        s0 = pdata.get("S0", [])
        model = pdata.get("model", args.model)
    else:
        theta = json.loads(args.theta)
        s0 = json.loads(args.s0) if args.s0 else []
        model = args.model

    return model, theta, s0


def build_octave_script(forcing_csv, model_name, theta, s0,
                        marrmot_path, delta_t, output_csv,
                        solver_tol, solver_maxiter):
    """
    Generate an Octave .m script that:
    1. Loads forcing data from CSV
    2. Creates model object
    3. Sets parameters, forcing, initial conditions
    4. Runs the model
    5. Writes outputs to CSV
    """
    theta_str = "[" + ", ".join(str(t) for t in theta) + "]"

    if s0:
        s0_str = "[" + ", ".join(str(s) for s in s0) + "]"
    else:
        s0_str = "zeros(1, m.numStores)"

    script = f"""\
% Auto-generated MARRMoT run script
% Do not edit -- generated by run_marrmot.py

% Add MARRMoT to path
addpath(genpath('{marrmot_path}'));

% Load optim package (Octave)
try
    pkg load optim;
catch
end

% Read forcing CSV (skip header lines starting with #)
fid = fopen('{forcing_csv}', 'r');
header_lines = 0;
while true
    line = fgetl(fid);
    if line(1) == '#'
        header_lines = header_lines + 1;
    else
        header_lines = header_lines + 1;  % column header
        break;
    end
end
fclose(fid);

data = csvread('{forcing_csv}', header_lines, 1);
% data columns: P, Ep, T (columns 2,3,4 after date)
P  = data(:, 1);
Ep = data(:, 2);
T  = data(:, 3);

fprintf('Loaded %d timesteps of forcing data\\n', length(P));
fprintf('P mean: %.2f mm/d, Ep mean: %.2f mm/d, T mean: %.2f C\\n', ...
    mean(P), mean(Ep), mean(T));

% Create model
m = feval('{model_name}');
fprintf('Model: %s (%d params, %d stores)\\n', ...
    '{model_name}', m.numParams, m.numStores);

% Set parameters
m.theta = {theta_str};

% Set forcing: [P, Ep, T] -- CRITICAL: this column order!
m.input_climate = [P, Ep, T];
m.delta_t = {delta_t};

% Set initial conditions
m.S0 = {s0_str};

% Solver options
m.solver_opts.resnorm_tolerance = {solver_tol};
m.solver_opts.resnorm_maxiter = {solver_maxiter};

% Run model
fprintf('Running model...\\n');
[fluxOutput, fluxInternal, storeInternal, waterBalance] = m.get_output();
fprintf('Model run complete.\\n');

% Extract total outflow Q (mm/d) and actual ET
Q = fluxOutput(:, 1);
if size(fluxOutput, 2) > 1
    Ea = fluxOutput(:, 2);
else
    % For simple models, estimate Ea from internal fluxes
    fn = fieldnames(fluxInternal);
    Ea = zeros(length(Q), 1);
    for i = 1:length(fn)
        if strncmp(fn{{i}}, 'ea', 2) || strncmp(fn{{i}}, 'Ea', 2)
            Ea = fluxInternal.(fn{{i}});
            break;
        end
    end
end

% Write output CSV
fid = fopen('{output_csv}', 'w');
fprintf(fid, 'timestep,Q_mm_d,Ea_mm_d\\n');
for i = 1:length(Q)
    fprintf(fid, '%d,%.6f,%.6f\\n', i, Q(i), Ea(i));
end
fclose(fid);
fprintf('Output written to {output_csv}\\n');

% Print water balance
fprintf('Water balance: %.4f mm\\n', waterBalance);

% Print summary stats
fprintf('SUMMARY_JSON_START\\n');
fprintf('{{"status":"success","n_timesteps":%d,"Q_mean":%.6f,"Q_max":%.6f,"Ea_mean":%.6f,"water_balance":%.6f}}\\n', ...
    length(Q), mean(Q), max(Q), mean(Ea), waterBalance);
fprintf('SUMMARY_JSON_END\\n');
"""
    return script


def process(args):
    """Build and execute Octave script."""
    model_name, theta, s0 = load_params(args)

    # Determine MARRMoT source path
    marrmot_path = args.marrmot_path
    if not marrmot_path:
        # Try common locations
        candidates = [
            "/home/server/knowledge-dissection-toolkit/auto_dissect/_work/MARRMoT/source/repo/MARRMoT",
            os.path.expanduser("~/MARRMoT/MARRMoT"),
            "./MARRMoT",
        ]
        for c in candidates:
            if os.path.isdir(c):
                marrmot_path = c
                break
        if not marrmot_path:
            return {"status": "error",
                    "errors": ["Cannot find MARRMoT source directory"]}

    # Prepare output paths
    output_dir = os.path.dirname(args.output) or "."
    os.makedirs(output_dir, exist_ok=True)
    output_csv = os.path.join(output_dir, "marrmot_timeseries.csv")

    # Build Octave script
    script = build_octave_script(
        forcing_csv=os.path.abspath(args.forcing),
        model_name=model_name,
        theta=theta,
        s0=s0,
        marrmot_path=os.path.abspath(marrmot_path),
        delta_t=args.delta_t,
        output_csv=os.path.abspath(output_csv),
        solver_tol=args.solver_tol,
        solver_maxiter=args.solver_maxiter,
    )

    # Write script to temp file
    with tempfile.NamedTemporaryFile(mode="w", suffix=".m",
                                      delete=False, dir=output_dir) as f:
        f.write(script)
        script_path = f.name

    print(f"Generated Octave script: {script_path}", file=sys.stderr)
    print(f"Model: {model_name}, theta={theta}, S0={s0}", file=sys.stderr)

    # Execute
    try:
        result = subprocess.run(
            ["octave", "--no-gui", "--no-window-system", script_path],
            capture_output=True, text=True,
            timeout=args.timeout,
            cwd=output_dir,
        )

        stdout = result.stdout
        stderr = result.stderr

        print(f"Octave exit code: {result.returncode}", file=sys.stderr)
        if stderr:
            print(f"Octave stderr:\n{stderr[:2000]}", file=sys.stderr)

        # Parse summary JSON from stdout
        summary = {}
        match = re.search(
            r'SUMMARY_JSON_START\s*\n(.*?)\nSUMMARY_JSON_END',
            stdout, re.DOTALL)
        if match:
            try:
                summary = json.loads(match.group(1).strip())
            except json.JSONDecodeError:
                pass

        run_result = {
            "status": "success" if result.returncode == 0 else "error",
            "model": model_name,
            "theta": theta,
            "S0": s0,
            "delta_t": args.delta_t,
            "output_csv": output_csv,
            "script_path": script_path,
            "return_code": result.returncode,
            "stdout_first_500": stdout[:500],
            "stderr_first_500": stderr[:500],
            "warnings": [],
        }
        run_result.update(summary)

        if result.returncode != 0:
            run_result["errors"] = [
                f"Octave exited with code {result.returncode}",
                stderr[:500],
            ]

    except subprocess.TimeoutExpired:
        run_result = {
            "status": "error",
            "errors": [f"Octave timed out after {args.timeout}s"],
            "model": model_name,
            "warnings": [],
        }
    finally:
        # Clean up temp script (keep for debugging if failed)
        if os.path.exists(script_path) and run_result.get("status") == "success":
            os.unlink(script_path)

    return run_result


def validate_outputs(result):
    """Validate execution outputs."""
    if result["status"] != "success":
        return result

    warnings = result.get("warnings", [])

    # Check output CSV exists
    if "output_csv" in result and not os.path.isfile(result["output_csv"]):
        warnings.append("Output CSV not created -- model may have failed")

    # Check water balance
    wb = result.get("water_balance", None)
    if wb is not None and abs(wb) > 1.0:
        warnings.append(
            f"Water balance error = {wb:.4f} mm (> 1 mm threshold, dt_014)")

    # Check Q values
    q_mean = result.get("Q_mean", None)
    if q_mean is not None and q_mean < 0:
        warnings.append("Negative mean Q -- check parameter configuration")
    if q_mean is not None and q_mean > 100:
        warnings.append("Mean Q > 100 mm/d -- possible unit error in forcing")

    result["warnings"] = warnings
    return result


def main():
    parser = argparse.ArgumentParser(
        description="Run MARRMoT model via Octave subprocess")
    parser.add_argument("--forcing", required=True,
                        help="Forcing CSV file (from convert_forcing.py)")
    parser.add_argument("--model", default=None,
                        help="Model name (e.g. m_29_hymod_5p_5s)")
    parser.add_argument("--params", default=None,
                        help="Parameter JSON file (from convert_parameters.py)")
    parser.add_argument("--theta", default=None,
                        help="Parameter vector as JSON array")
    parser.add_argument("--s0", default=None,
                        help="Initial storage vector as JSON array")
    parser.add_argument("--delta-t", type=float, default=1.0,
                        help="Time step in days (default: 1)")
    parser.add_argument("--output", required=True,
                        help="Output JSON file")
    parser.add_argument("--marrmot-path", default=None,
                        help="Path to MARRMoT source directory")
    parser.add_argument("--solver-tol", type=float, default=0.1,
                        help="Solver residual tolerance")
    parser.add_argument("--solver-maxiter", type=int, default=6,
                        help="Solver max re-runs")
    parser.add_argument("--timeout", type=int, default=600,
                        help="Execution timeout in seconds")

    args = parser.parse_args()
    validate_inputs(args)
    result = process(args)
    result = validate_outputs(result)

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(result, f, indent=2)

    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
