#!/usr/bin/env python3
"""
configure_w2_outflow.py — Configure CE-QUAL-W2 dam outlet structures and outflow.

Generates outflow time series file (qot_*.npt) and outlet configuration parameters.

CRITICAL (dt_018): Outlet elevation must be in m ASL matching the bathymetry datum.
If elevation is depth-from-surface, the selective withdrawal draws from the wrong level.

CRITICAL (dt_019): Outflow must be in m^3/s. If units are wrong (e.g., L/s), the
reservoir drains unrealistically fast or the water balance is broken.

Selective withdrawal modes:
  - constant: fixed outflow rate (simplest)
  - time_series: specified outflow at each time step
  - rule_based: outlet selection based on reservoir level
  - multi_level: time-varying switching between outlet elevations

Usage:
    python configure_w2_outflow.py \
        --mode constant --outflow_m3s 50.0 \
        --outlet_elevation 120.0 \
        --start_jday 1 --end_jday 365 \
        --output_dir /path/to/output
"""

import argparse
import json
import os
import sys

import numpy as np


def validate_inputs(args):
    """Validate inputs."""
    errors = []
    if args.mode == "constant" and args.outflow_m3s is None:
        errors.append("--outflow_m3s required for constant mode")
    if args.outlet_elevation is None:
        errors.append("--outlet_elevation required")
    if errors:
        print(json.dumps({"status": "error", "errors": errors}))
        sys.exit(1)


def process(args):
    """Main processing."""
    os.makedirs(args.output_dir, exist_ok=True)

    # Generate outflow time series
    if args.mode == "constant":
        # Simple constant outflow
        n_days = int(args.end_jday - args.start_jday + 1)
        jdays = np.linspace(args.start_jday, args.end_jday, n_days)
        outflow = np.full(n_days, args.outflow_m3s)
    elif args.mode == "time_series" and args.outflow_csv:
        import pandas as pd
        df = pd.read_csv(args.outflow_csv)
        jdays = df.iloc[:, 0].values
        outflow = df.iloc[:, 1].values
    else:
        # Default: constant moderate outflow
        n_days = int(args.end_jday - args.start_jday + 1)
        jdays = np.linspace(args.start_jday, args.end_jday, n_days)
        outflow = np.full(n_days, 10.0)  # default 10 m3/s

    # Write qot file
    qot_path = os.path.join(args.output_dir, f"qot_br{args.branch_id}.npt")
    with open(qot_path, "w") as f:
        f.write(f"$Outflow for branch {args.branch_id} — generated by HydroCraft\n")
        f.write(f"$JDAY          QOT\n")
        for i in range(len(jdays)):
            f.write(f"{jdays[i]:10.3f}{outflow[i]:10.3f}\n")

    # Outflow configuration
    config = {
        "mode": args.mode,
        "n_outlets": args.n_outlets if args.n_outlets else 1,
        "outlet_elevation_m_asl": args.outlet_elevation,
        "outlet_width_m": args.outlet_width if args.outlet_width else 10.0,
        "branch_id": args.branch_id,
        "mean_outflow_m3s": round(float(np.mean(outflow)), 2),
        "max_outflow_m3s": round(float(np.max(outflow)), 2),
    }

    config_path = os.path.join(args.output_dir, "outflow_config.json")
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)

    result = {
        "status": "success",
        "qot_file": qot_path,
        "config_file": config_path,
        "n_outlets": config["n_outlets"],
        "outlet_elevation_m_asl": config["outlet_elevation_m_asl"],
        "mean_outflow_m3s": config["mean_outflow_m3s"],
    }

    print(json.dumps(result, indent=2))
    return 0


def main():
    parser = argparse.ArgumentParser(description="Configure CE-QUAL-W2 outflow")
    parser.add_argument("--mode", default="constant", choices=["constant", "time_series", "rule_based"])
    parser.add_argument("--outflow_m3s", type=float, help="Constant outflow rate (m^3/s)")
    parser.add_argument("--outflow_csv", help="Time series CSV (jday, outflow_m3s)")
    parser.add_argument("--outlet_elevation", type=float, help="Outlet elevation (m ASL)")
    parser.add_argument("--outlet_width", type=float, default=10.0, help="Outlet width (m)")
    parser.add_argument("--n_outlets", type=int, default=1, help="Number of outlet structures")
    parser.add_argument("--branch_id", type=int, default=1)
    parser.add_argument("--start_jday", type=float, default=1.0)
    parser.add_argument("--end_jday", type=float, default=365.0)
    parser.add_argument("--output_dir", required=True)
    args = parser.parse_args()
    validate_inputs(args)
    sys.exit(process(args))


if __name__ == "__main__":
    main()
