#!/usr/bin/env python3
"""
Generate GeoClass.txt for HYPE from SLC definitions.

Reads SLC definitions (landuse, soil type pairs) and generates the
GeoClass.txt file with proper soil layer depths.

Usage:
    python generate_geoclass.py \
        --slc_defs outputs/hype_run/slc/slc_definitions.csv \
        --output outputs/hype_run/modelfiles/GeoClass.txt
"""

import argparse
import sys
import os
from pathlib import Path

# Default soil layer depths by soil type (meters)
# Based on World-Wide HYPE defaults
DEFAULT_SOIL_DEPTHS = {
    1: [0.3, 0.6, 1.5],   # Coarse (sandy/till)
    2: [0.3, 0.9, 1.8],   # Medium (loam/silt)
    3: [0.2, 0.5, 1.2],   # Fine (clay)
    4: [0.3, 0.8, 1.5],   # Organic (peat)
}

# Vegetation type by land use
LANDUSE_VEGTYPE = {
    1: 1,  # Forest -> conifer (default)
    2: 3,  # Open land/crop -> grass
    3: 0,  # Water -> no vegetation
    4: 0,  # Urban -> no vegetation
    5: 0,  # Glacier -> no vegetation
}

# Special class codes
SPECIAL_CODES = {
    3: 2,  # Water -> special=2 (lake/river)
    5: 3,  # Glacier -> special=3
}


def generate_geoclass(slc_defs_path, output_path, soil_depths=None):
    """
    Generate GeoClass.txt from SLC definitions.

    Args:
        slc_defs_path: Path to slc_definitions.csv (SLC_ID, LANDUSE, SOIL)
        output_path: Output GeoClass.txt path
        soil_depths: Optional dict mapping soil_type -> [depth1, depth2, depth3]
    """
    if soil_depths is None:
        soil_depths = DEFAULT_SOIL_DEPTHS

    # Read SLC definitions
    slc_defs = []
    with open(slc_defs_path) as f:
        header = f.readline()  # skip header
        for line in f:
            parts = line.strip().split('\t')
            if len(parts) >= 3:
                slc_defs.append({
                    'id': int(parts[0]),
                    'landuse': int(parts[1]),
                    'soil': int(parts[2]),
                })

    # Generate GeoClass.txt
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)

    with open(output_path, 'w') as f:
        f.write("!! GeoClass.txt generated by HydroCraft HYPE tools\n")
        f.write("!! SLC_ID  landuse  soil  crop  crop2  rotation  vegtype  special  tiledepth  streamdepth  numlayers  soildepth1  [soildepth2]  [soildepth3]\n")

        for slc in slc_defs:
            lu = slc['landuse']
            so = slc['soil']
            vegtype = LANDUSE_VEGTYPE.get(lu, 0)
            special = SPECIAL_CODES.get(lu, 0)
            crop = 1 if lu == 2 else 0  # Crop class for agricultural land
            tiledepth = 0.8 if lu == 2 else 0  # Tile drainage for cropland

            if lu == 3:  # Water class: 1 layer, deep
                numlayers = 1
                depths = [5.0]
            else:
                depths = soil_depths.get(so, [0.3, 0.6, 1.5])
                numlayers = len(depths)

            # Build line
            parts = [
                str(slc['id']),   # SLC ID
                str(lu),          # landuse
                str(so),          # soil
                str(crop),        # crop
                '0',              # crop2
                '0',              # rotation
                str(vegtype),     # vegtype
                str(special),     # special
                f'{tiledepth}',   # tiledepth
                '0',              # streamdepth
                str(numlayers),   # numlayers
            ]
            for d in depths:
                parts.append(f'{d}')

            f.write('\t'.join(parts) + '\n')

    print(f"Generated GeoClass.txt with {len(slc_defs)} SLC classes: {output_path}")

    # Print summary
    for slc in slc_defs:
        lu_name = {1: 'forest', 2: 'crop/open', 3: 'water', 4: 'urban', 5: 'glacier'}.get(slc['landuse'], '?')
        so_name = {1: 'coarse', 2: 'medium', 3: 'fine', 4: 'organic'}.get(slc['soil'], '?')
        print(f"  SLC_{slc['id']}: {lu_name}/{so_name}")


def main():
    parser = argparse.ArgumentParser(description='Generate HYPE GeoClass.txt')
    parser.add_argument('--slc_defs', required=True, help='SLC definitions CSV')
    parser.add_argument('--output', required=True, help='Output GeoClass.txt path')

    args = parser.parse_args()
    generate_geoclass(args.slc_defs, args.output)


if __name__ == '__main__':
    main()
