#!/usr/bin/env python3
"""Preflight check for openAMUNDSEN — auto-generated by KDT v5.0"""
import os, sys, shutil

PASS = FAIL = 0
MODEL_NAME = "openAMUNDSEN"

def check_file(path, label, executable=False):
    global PASS, FAIL
    if os.path.isfile(path):
        if executable and not os.access(path, os.X_OK):
            print(f"  WARN  {label}: exists but not executable: {path}")
            FAIL += 1
        else:
            print(f"  OK    {label}: {path}")
            PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_dir(path, label):
    global PASS, FAIL
    if os.path.isdir(path):
        print(f"  OK    {label}: {path} ({len(os.listdir(path))} items)")
        PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_import(module, label):
    # Also search HydroCraft python_env for packages
    import sys
    _penv = "KISSPATH_PYTHON_ENV/lib/python3.12/site-packages"
    if _penv not in sys.path:
        sys.path.insert(0, _penv)
    global PASS, FAIL
    try:
        __import__(module)
        print(f"  OK    {label}: import {module}")
        PASS += 1
    except ImportError as e:
        print(f"  FAIL  {label}: {e}")
        print(f"         Fix: pip install {module.split('.')[0]}")
        FAIL += 1

def main():
    global PASS, FAIL
    print(f"{' PREFLIGHT: openAMUNDSEN ':=^60}")
    print()
    # openAMUNDSEN in dissection venv
    import sys
    # openAMUNDSEN: use venv python (has deps system python lacks)
    import subprocess
    try:
        proc = subprocess.run([sys.executable, "-c", "import openamundsen"], 
            capture_output=True, timeout=10)
        if proc.returncode == 0:
            print(f"  OK    openAMUNDSEN (openamundsen): verified via venv python")
            PASS += 1
        else:
            print(f"  FAIL  openAMUNDSEN (openamundsen): {proc.stderr.decode().strip().split(chr(10))[-1]}")
            FAIL += 1
    except Exception as e:
        print(f"  FAIL  openAMUNDSEN (openamundsen): {e}")
        FAIL += 1
    # Check diagnostics
    ki_dir = os.path.dirname(os.path.abspath(__file__))
    triplets = os.path.join(ki_dir, "diagnostics", "triplets.yaml")
    if os.path.isfile(triplets):
        print(f"  INFO  Diagnostics available: {triplets}")

    print(f"\n  Results: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL > 0 else 0)

if __name__ == "__main__":
    main()
