#!/usr/bin/env python3
"""
Generate par.txt for HYPE with default or literature-based parameter values.

Reads GeoClass.txt to determine the number of land-use and soil types,
then writes par.txt with the correct number of values per parameter.

Usage:
    python setup_parameters.py \
        --geoclass outputs/hype_run/modelfiles/GeoClass.txt \
        --output outputs/hype_run/modelfiles/par.txt \
        --climate humid_subtropical
"""

import argparse
import sys
import os
from pathlib import Path


# Default parameter values by climate zone
# Based on World-Wide HYPE (WWH) calibrated values
PARAMETER_DEFAULTS = {
    'humid_subtropical': {
        'ttmp': 0.0,       # snow threshold (C)
        'cmlt': 4.0,       # degree-day factor (mm/C/day)
        'cevp': 0.20,      # PET coefficient
        'srrcs': 0.05,     # surface runoff recession
        'wcfc': 0.20,      # field capacity
        'wcwp': 0.08,      # wilting point
        'wcep': 0.40,      # effective porosity
        'rrcs1': 0.08,     # upper soil recession
        'rrcs2': 0.01,     # lower soil recession
        'rrcs3': 0.001,    # deep groundwater recession
        'lp': 0.8,         # PET reduction threshold
        'rivvel': 1.0,     # river velocity (m/s)
        'damp': 0.5,       # damping coefficient
        'cevpam': 0.3,     # PET amplitude
        'cevpph': 30,      # PET phase shift (days)
    },
    'semi_arid': {
        'ttmp': 0.0,
        'cmlt': 3.0,
        'cevp': 0.30,
        'srrcs': 0.10,
        'wcfc': 0.15,
        'wcwp': 0.05,
        'wcep': 0.35,
        'rrcs1': 0.15,
        'rrcs2': 0.02,
        'rrcs3': 0.002,
        'lp': 0.6,
        'rivvel': 0.8,
        'damp': 0.3,
        'cevpam': 0.4,
        'cevpph': 20,
    },
    'cold_alpine': {
        'ttmp': -1.0,
        'cmlt': 3.5,
        'cevp': 0.12,
        'srrcs': 0.03,
        'wcfc': 0.18,
        'wcwp': 0.06,
        'wcep': 0.38,
        'rrcs1': 0.10,
        'rrcs2': 0.008,
        'rrcs3': 0.0005,
        'lp': 0.9,
        'rivvel': 1.5,
        'damp': 0.6,
        'cevpam': 0.25,
        'cevpph': 40,
    },
    'tropical': {
        'ttmp': 0.0,
        'cmlt': 5.0,
        'cevp': 0.25,
        'srrcs': 0.03,
        'wcfc': 0.25,
        'wcwp': 0.10,
        'wcep': 0.45,
        'rrcs1': 0.05,
        'rrcs2': 0.008,
        'rrcs3': 0.001,
        'lp': 0.9,
        'rivvel': 0.8,
        'damp': 0.5,
        'cevpam': 0.1,
        'cevpph': 10,
    },
}

# Parameter categorization
LANDUSE_PARAMS = ['ttmp', 'cmlt', 'cevp', 'srrcs']
SOIL_PARAMS = ['wcfc', 'wcwp', 'wcep', 'rrcs1', 'rrcs2']
GENERAL_PARAMS = ['rrcs3', 'lp', 'rivvel', 'damp', 'cevpam', 'cevpph']

# Soil-type specific adjustments (multiplier relative to default)
SOIL_ADJUSTMENTS = {
    # soil_type: {param: multiplier}
    1: {'wcfc': 0.7, 'wcwp': 0.6, 'wcep': 0.9, 'rrcs1': 1.5, 'rrcs2': 1.5},   # Coarse
    2: {'wcfc': 1.0, 'wcwp': 1.0, 'wcep': 1.0, 'rrcs1': 1.0, 'rrcs2': 1.0},   # Medium (reference)
    3: {'wcfc': 1.3, 'wcwp': 1.4, 'wcep': 0.8, 'rrcs1': 0.5, 'rrcs2': 0.5},   # Fine
    4: {'wcfc': 1.2, 'wcwp': 0.8, 'wcep': 1.3, 'rrcs1': 0.8, 'rrcs2': 0.8},   # Organic
}


def read_geoclass(filepath):
    """Read GeoClass.txt and return landuse/soil type counts."""
    landuse_ids = set()
    soil_ids = set()

    with open(filepath) as f:
        for line in f:
            if line.startswith('!!') or line.strip() == '':
                continue
            parts = line.strip().split()
            if len(parts) >= 3:
                try:
                    slc_id = int(parts[0])
                    landuse = int(parts[1])
                    soil = int(parts[2])
                    landuse_ids.add(landuse)
                    soil_ids.add(soil)
                except ValueError:
                    continue

    return sorted(landuse_ids), sorted(soil_ids)


def generate_par_txt(geoclass_path, output_path, climate='humid_subtropical'):
    """Generate par.txt with correct parameter counts."""
    landuse_ids, soil_ids = read_geoclass(geoclass_path)
    n_landuse = max(landuse_ids)
    n_soil = max(soil_ids)

    defaults = PARAMETER_DEFAULTS.get(climate, PARAMETER_DEFAULTS['humid_subtropical'])

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)

    with open(output_path, 'w') as f:
        f.write(f"!! par.txt generated by HydroCraft HYPE tools\n")
        f.write(f"!! Climate zone: {climate}\n")
        f.write(f"!! Land use types: {n_landuse}, Soil types: {n_soil}\n")
        f.write(f"!!\n")

        # Land use dependent parameters
        f.write(f"!! Land use dependent parameters ({n_landuse} values each)\n")
        for param in LANDUSE_PARAMS:
            base_val = defaults[param]
            values = []
            for lu in range(1, n_landuse + 1):
                if lu == 3:  # Water class
                    values.append('0')
                else:
                    values.append(f'{base_val}')
            f.write(f"{param}\t" + "\t".join(values) + "\n")

        f.write(f"!! Soil type dependent parameters ({n_soil} values each)\n")
        for param in SOIL_PARAMS:
            base_val = defaults[param]
            values = []
            for so in range(1, n_soil + 1):
                adj = SOIL_ADJUSTMENTS.get(so, {}).get(param, 1.0)
                val = base_val * adj
                # Ensure physical constraints: wcwp < wcfc < wcep
                values.append(f'{val:.4f}')
            f.write(f"{param}\t" + "\t".join(values) + "\n")

        f.write(f"!! General parameters (1 value each)\n")
        for param in GENERAL_PARAMS:
            val = defaults[param]
            if isinstance(val, int):
                f.write(f"{param}\t{val}\n")
            else:
                f.write(f"{param}\t{val}\n")

    print(f"Generated par.txt: {output_path}")
    print(f"  Climate zone: {climate}")
    print(f"  Land use types: {n_landuse}")
    print(f"  Soil types: {n_soil}")
    print(f"  Parameters: {len(LANDUSE_PARAMS)} land-use + {len(SOIL_PARAMS)} soil + {len(GENERAL_PARAMS)} general")


def main():
    parser = argparse.ArgumentParser(description='Generate HYPE par.txt')
    parser.add_argument('--geoclass', required=True, help='GeoClass.txt path')
    parser.add_argument('--output', required=True, help='Output par.txt path')
    parser.add_argument('--climate', default='humid_subtropical',
                       choices=list(PARAMETER_DEFAULTS.keys()),
                       help='Climate zone for default parameters')

    args = parser.parse_args()
    generate_par_txt(args.geoclass, args.output, args.climate)


if __name__ == '__main__':
    main()
