#!/usr/bin/env python3
"""
generate_config.py — COAWST Configuration Generator
====================================================

Generates ROMS ocean.in, MCT coupling.in, and SWAN input files from
a parameter dictionary. Validates parameter consistency across models
before writing.

CRITICAL CHECKS (silent failures if wrong):
  - NtileI × NtileJ MUST equal MPI processor count (dt_004)
  - DT × NDTFAST should satisfy CFL for barotropic mode (dt_005)
  - Coupling intervals must be integer multiples of model timesteps (dt_010)
  - BULK_FLUXES flag must match forcing file type (dt_006)
  - Grid dimensions (Lm, Mm) must match grid NetCDF dimensions
  - Vtransform/Vstretching must match IC/BC files

Usage:
  python3 generate_config.py \\
    --grid sandy_grid.nc \\
    --application SANDY \\
    --nprocs 16 --ntile-i 4 --ntile-j 4 \\
    --dt 60.0 --ndtfast 30 \\
    --ntimes 43200 \\
    --output-dir Projects/Sandy/ \\
    --coupled --swan --wrf

  python3 generate_config.py \\
    --grid upwelling_grid.nc \\
    --application UPWELLING \\
    --nprocs 4 --ntile-i 2 --ntile-j 2 \\
    --dt 300.0 --ndtfast 20 \\
    --ntimes 4320 \\
    --output-dir Projects/Upwelling/

See diagnostics/triplets.yaml dt_004, dt_005, dt_006, dt_010, dt_014.
"""

import argparse
import json
import math
import os
import sys
from datetime import datetime

import numpy as np

try:
    import netCDF4 as nc
    HAS_NETCDF = True
except ImportError:
    HAS_NETCDF = False


def validate_inputs(args):
    """Validate configuration parameters."""
    errors = []
    warnings = []

    # Check tiling matches nprocs
    ocean_procs = args.ntile_i * args.ntile_j
    total_procs = ocean_procs
    if args.coupled:
        if args.nprocs_wav is None:
            args.nprocs_wav = 0
        if args.nprocs_atm is None:
            args.nprocs_atm = 0
        total_procs = ocean_procs + args.nprocs_wav + args.nprocs_atm
    if total_procs != args.nprocs:
        errors.append(
            f"FATAL (dt_004): NtileI({args.ntile_i}) × NtileJ({args.ntile_j}) = {ocean_procs} "
            f"ocean procs. Total allocated = {total_procs}, but --nprocs = {args.nprocs}. "
            f"These MUST match or MPI will deadlock."
        )

    # CFL check for barotropic mode
    if args.grid and os.path.exists(args.grid) and HAS_NETCDF:
        try:
            ds = nc.Dataset(args.grid)
            h = ds.variables["h"][:]
            pm = ds.variables["pm"][:] if "pm" in ds.variables else None
            pn = ds.variables["pn"][:] if "pn" in ds.variables else None
            ds.close()

            if pm is not None and pn is not None:
                dx_min = 1.0 / np.max(pm)
                dy_min = 1.0 / np.max(pn)
                h_max = np.max(h)
                c_max = np.sqrt(9.81 * h_max)  # shallow water wave speed
                dt_baro = args.dt / args.ndtfast
                cfl = c_max * dt_baro / min(dx_min, dy_min)
                if cfl > 0.7:
                    warnings.append(
                        f"CFL WARNING (dt_005): barotropic CFL = {cfl:.3f} > 0.7. "
                        f"Reduce DT or increase NDTFAST. "
                        f"(c_max={c_max:.1f} m/s, dt_baro={dt_baro:.2f} s, dx_min={dx_min:.0f} m)"
                    )
                else:
                    print(f"  CFL check OK: {cfl:.3f}", file=sys.stderr)
        except Exception as e:
            warnings.append(f"Could not check CFL: {e}")
    elif args.grid and not os.path.exists(args.grid):
        errors.append(f"Grid file not found: {args.grid}")

    # Coupling interval check
    if args.coupled and args.coupling_dt:
        if args.coupling_dt % args.dt != 0:
            warnings.append(
                f"Coupling interval ({args.coupling_dt}s) is not an integer multiple "
                f"of ocean DT ({args.dt}s). This will cause coupling desynchronization (dt_010)."
            )

    if errors:
        print(json.dumps({"status": "error", "errors": errors, "warnings": warnings}, indent=2))
        sys.exit(1)

    return warnings


def read_grid_dims(grid_path):
    """Read grid dimensions from NetCDF grid file."""
    ds = nc.Dataset(grid_path)
    xi_rho = len(ds.dimensions["xi_rho"])
    eta_rho = len(ds.dimensions["eta_rho"])
    ds.close()
    Lm = xi_rho - 2
    Mm = eta_rho - 2
    return Lm, Mm


def generate_ocean_in(args, Lm, Mm, warnings):
    """Generate ROMS ocean.in configuration file."""
    ngrids = 1

    lines = []
    lines.append("! ROMS ocean.in — generated by generate_config.py")
    lines.append(f"! Application: {args.application}")
    lines.append(f"! Generated: {datetime.now().isoformat()}")
    lines.append("!")

    # Application title
    lines.append(f"       TITLE = {args.application} COAWST simulation")
    lines.append("")

    # Time stepping
    lines.append(f"     MyAppCPP = {args.application}")
    lines.append(f"      VARNAME = ROMS/External/varinfo.yaml")
    lines.append(f"       Ngrids = {ngrids}")
    lines.append(f"      NtileI == {args.ntile_i}")
    lines.append(f"      NtileJ == {args.ntile_j}")
    lines.append("")

    # Grid dimensions
    lines.append(f"          Lm == {Lm}     ! Number of I-direction INTERIOR RHO-points")
    lines.append(f"          Mm == {Mm}     ! Number of J-direction INTERIOR RHO-points")
    lines.append(f"           N == {args.n_levels}     ! Number of vertical levels")
    lines.append(f"         NAT =  2     ! Number of active tracers (temp + salt)")
    lines.append("")

    # Vertical coordinate parameters
    lines.append(f"  Vtransform == {args.vtransform}")
    lines.append(f" Vstretching == {args.vstretching}")
    lines.append(f"     THETA_S == {args.theta_s}")
    lines.append(f"     THETA_B == {args.theta_b}")
    lines.append(f"      TCLINE == {args.tcline}")
    lines.append("")

    # Time stepping
    lines.append(f"          DT == {args.dt:g}d0     ! Baroclinic timestep (seconds)")
    lines.append(f"     NDTFAST == {args.ndtfast}     ! Barotropic/Baroclinic ratio")
    lines.append("")

    # Run length
    lines.append(f"      NTIMES == {args.ntimes}")
    lines.append(f"        NRST == {args.ntimes}     ! Restart interval (timesteps)")
    lines.append(f"        NHIS == {max(1, args.ntimes // 100)}     ! History output interval")
    lines.append(f"        NAVG == {max(1, args.ntimes // 20)}     ! Average output interval")
    lines.append(f"       NDEFHIS == 0     ! One history file")
    lines.append("")

    # Time reference
    time_ref = args.time_ref if args.time_ref else "20120101.0d0"
    lines.append(f"     TIME_REF = {time_ref}")
    lines.append("")

    # Horizontal mixing
    lines.append(f"       VISC2 == 5.0d0     ! Laplacian horizontal viscosity (m²/s)")
    lines.append(f"        TNU2 == 5.0d0  5.0d0     ! Tracer horizontal diffusion (m²/s)")
    lines.append("")

    # Bottom drag
    lines.append(f"       RDRG2 == 3.0d-3     ! Quadratic bottom drag coefficient")
    lines.append("")

    # Nudging
    lines.append(f"       TNUDG == 10.0d0  10.0d0     ! Tracer nudging timescale (days)")
    lines.append(f"       ZNUDG == 1.0d0     ! Free-surface nudging timescale (days)")
    lines.append(f"      M2NUDG == 1.0d0     ! 2D momentum nudging timescale (days)")
    lines.append(f"      M3NUDG == 1.0d0     ! 3D momentum nudging timescale (days)")
    lines.append("")

    # Lateral boundary conditions
    lines.append("         LBC(isFsur) == Cha     Cha     Cha     Cha")
    lines.append("         LBC(isUbar) == Fla     Fla     Fla     Fla")
    lines.append("         LBC(isVbar) == Fla     Fla     Fla     Fla")
    lines.append("         LBC(isUvel) == RadNud  RadNud  RadNud  RadNud")
    lines.append("         LBC(isVvel) == RadNud  RadNud  RadNud  RadNud")
    lines.append("         LBC(isTvar) == RadNud  RadNud  RadNud  RadNud \\")
    lines.append("                        RadNud  RadNud  RadNud  RadNud")
    lines.append("")

    # I/O files
    lines.append(f"      GRDNAME == {args.grid}")
    lines.append(f"      ININAME == {args.ini if args.ini else 'ocean_ini.nc'}")
    if args.bry:
        lines.append(f"      BRYNAME == {args.bry}")
    if args.frc:
        lines.append(f"      FRCNAME == {args.frc}")
    if args.clm:
        lines.append(f"      CLMNAME == {args.clm}")
    lines.append(f"      HISNAME == {args.application.lower()}_his.nc")
    lines.append(f"      AVGNAME == {args.application.lower()}_avg.nc")
    lines.append(f"      RSTNAME == {args.application.lower()}_rst.nc")
    lines.append("")

    return "\n".join(lines)


def generate_coupling_in(args, warnings):
    """Generate MCT coupling.in configuration file."""
    coupling_dt = args.coupling_dt if args.coupling_dt else 600.0
    nprocs_ocn = args.ntile_i * args.ntile_j
    nprocs_wav = args.nprocs_wav if args.nprocs_wav else 0
    nprocs_atm = args.nprocs_atm if args.nprocs_atm else 0

    lines = []
    lines.append("! COAWST coupling.in — generated by generate_config.py")
    lines.append(f"! Generated: {datetime.now().isoformat()}")
    lines.append("!")
    lines.append(f"    Nmodels = {'3' if args.wrf else '2'}")
    lines.append("")

    if args.wrf:
        lines.append(f"   NnodesATM =  {nprocs_atm}")
    lines.append(f"   NnodesWAV =  {nprocs_wav}")
    lines.append(f"   NnodesOCN =  {nprocs_ocn}")
    lines.append("")

    # Coupling intervals (seconds)
    if args.wrf:
        lines.append(f"    TI_ATM2WAV = {coupling_dt:g}")
        lines.append(f"    TI_ATM2OCN = {coupling_dt:g}")
        lines.append(f"    TI_WAV2ATM = {coupling_dt:g}")
        lines.append(f"    TI_OCN2ATM = {coupling_dt:g}")
    lines.append(f"    TI_WAV2OCN = {coupling_dt:g}")
    lines.append(f"    TI_OCN2WAV = {coupling_dt:g}")
    lines.append("")

    # SCRIP weights
    lines.append("    SCRIP_WEIGHT_OPTION = 1")
    lines.append(f"    SCRIP_COAWST_NAME = scrip_weights.nc")
    lines.append("")

    return "\n".join(lines)


def generate_swan_in(args, warnings):
    """Generate SWAN input file for coupled simulation."""
    lines = []
    lines.append(f"$ SWAN input — generated by generate_config.py")
    lines.append(f"$ Application: {args.application}")
    lines.append(f"$")
    lines.append(f"MODE NONSTATIONARY TWODIMENSIONAL")
    lines.append(f"COORDINATES SPHERICAL")
    lines.append(f"$")

    # Computational grid (matched to ROMS grid)
    lines.append(f"CGRID REGULAR 0.0 0.0 0.0 1.0 1.0 99 99 CIRCLE 36 0.04 1.0 31")
    lines.append(f"$")

    # Physics
    lines.append(f"GEN3 KOMEN")
    lines.append(f"BREAKING CONSTANT 1.0 0.73")
    lines.append(f"FRICTION JONSWAP 0.067")
    lines.append(f"TRIAD")
    lines.append(f"$")

    # Numerics
    lines.append(f"PROP BSBT")
    lines.append(f"NUM ACCUR 0.02 0.02 0.02 98 NONSTAT 20")
    lines.append(f"$")

    # Output
    lines.append(f"OUTPUT OPTIONS '%' TABLE 16 BLOCK 8 8")
    lines.append(f"$")

    # Check spectral resolution
    n_dirs = 36
    n_freqs = 31
    if n_dirs < 24:
        warnings.append(f"SWAN direction bins ({n_dirs}) < 24 — directional spreading smeared (dt_014)")
    if n_freqs < 25:
        warnings.append(f"SWAN frequency bins ({n_freqs}) < 25 — may miss swell-sea separation (dt_014)")

    return "\n".join(lines)


def process(args, warnings):
    """Generate all configuration files."""
    os.makedirs(args.output_dir, exist_ok=True)

    # Read grid dimensions
    Lm, Mm = 0, 0
    if args.grid and os.path.exists(args.grid) and HAS_NETCDF:
        Lm, Mm = read_grid_dims(args.grid)
        print(f"  Grid dimensions from file: Lm={Lm}, Mm={Mm}", file=sys.stderr)
    else:
        Lm = args.lm if args.lm else 100
        Mm = args.mm if args.mm else 100
        warnings.append(f"Using provided/default grid dims: Lm={Lm}, Mm={Mm}")

    files_written = []

    # Ocean.in
    ocean_content = generate_ocean_in(args, Lm, Mm, warnings)
    ocean_path = os.path.join(args.output_dir, f"ocean_{args.application.lower()}.in")
    with open(ocean_path, "w") as f:
        f.write(ocean_content)
    files_written.append(ocean_path)
    print(f"  Written: {ocean_path}", file=sys.stderr)

    # Coupling.in (if coupled)
    if args.coupled:
        coupling_content = generate_coupling_in(args, warnings)
        coupling_path = os.path.join(args.output_dir, f"coupling_{args.application.lower()}.in")
        with open(coupling_path, "w") as f:
            f.write(coupling_content)
        files_written.append(coupling_path)
        print(f"  Written: {coupling_path}", file=sys.stderr)

    # SWAN input (if wave coupling)
    if args.swan:
        swan_content = generate_swan_in(args, warnings)
        swan_path = os.path.join(args.output_dir, f"swan_{args.application.lower()}.in")
        with open(swan_path, "w") as f:
            f.write(swan_content)
        files_written.append(swan_path)
        print(f"  Written: {swan_path}", file=sys.stderr)

    return {
        "status": "success",
        "files_written": files_written,
        "grid_dims": {"Lm": Lm, "Mm": Mm},
        "warnings": warnings,
    }


def validate_outputs(result):
    """Verify output files exist and are non-empty."""
    if result["status"] != "success":
        return result

    for fpath in result.get("files_written", []):
        if not os.path.exists(fpath):
            result.setdefault("errors", []).append(f"File not created: {fpath}")
            result["status"] = "error"
        elif os.path.getsize(fpath) == 0:
            result["warnings"].append(f"File is empty: {fpath}")

    return result


def main():
    parser = argparse.ArgumentParser(
        description="Generate COAWST configuration files (ocean.in, coupling.in, swan.in)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Required
    parser.add_argument("--grid", required=True, help="ROMS grid NetCDF file")
    parser.add_argument("--application", required=True, help="ROMS_APPLICATION name (e.g., SANDY)")
    parser.add_argument("--nprocs", type=int, required=True, help="Total MPI processor count")
    parser.add_argument("--ntile-i", type=int, required=True, help="Tiles in I (xi) direction")
    parser.add_argument("--ntile-j", type=int, required=True, help="Tiles in J (eta) direction")
    parser.add_argument("--dt", type=float, required=True, help="Baroclinic timestep (seconds)")
    parser.add_argument("--ndtfast", type=int, required=True, help="Barotropic:baroclinic ratio")
    parser.add_argument("--ntimes", type=int, required=True, help="Total number of timesteps")
    parser.add_argument("--output-dir", required=True, help="Output directory")

    # Optional
    parser.add_argument("--n-levels", type=int, default=16, help="Vertical levels (default: 16)")
    parser.add_argument("--vtransform", type=int, default=2, help="S-coord transform (default: 2)")
    parser.add_argument("--vstretching", type=int, default=4, help="S-coord stretching (default: 4)")
    parser.add_argument("--theta-s", type=float, default=7.0, help="Surface stretching (default: 7.0)")
    parser.add_argument("--theta-b", type=float, default=2.0, help="Bottom stretching (default: 2.0)")
    parser.add_argument("--tcline", type=float, default=200.0, help="Thermocline depth (default: 200m)")
    parser.add_argument("--time-ref", default=None, help="Time reference (e.g., 20120101.0d0)")
    parser.add_argument("--ini", default=None, help="Initial condition file")
    parser.add_argument("--bry", default=None, help="Boundary condition file")
    parser.add_argument("--frc", default=None, help="Forcing file")
    parser.add_argument("--clm", default=None, help="Climatology file")
    parser.add_argument("--lm", type=int, default=None, help="Manual Lm if grid not readable")
    parser.add_argument("--mm", type=int, default=None, help="Manual Mm if grid not readable")

    # Coupling
    parser.add_argument("--coupled", action="store_true", help="Enable model coupling")
    parser.add_argument("--swan", action="store_true", help="Include SWAN wave model")
    parser.add_argument("--wrf", action="store_true", help="Include WRF atmosphere model")
    parser.add_argument("--coupling-dt", type=float, default=600.0, help="Coupling interval (seconds)")
    parser.add_argument("--nprocs-wav", type=int, default=0, help="Processors for wave model")
    parser.add_argument("--nprocs-atm", type=int, default=0, help="Processors for atmosphere model")

    args = parser.parse_args()
    warnings = validate_inputs(args)
    result = process(args, warnings)
    result = validate_outputs(result)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
