#!/usr/bin/env python3
"""Preflight check for CWatM — auto-generated by KDT v5.0"""
import os, sys, shutil

PASS = FAIL = 0
MODEL_NAME = "CWatM"

def check_file(path, label, executable=False):
    global PASS, FAIL
    if os.path.isfile(path):
        if executable and not os.access(path, os.X_OK):
            print(f"  WARN  {label}: exists but not executable: {path}")
            FAIL += 1
        else:
            print(f"  OK    {label}: {path}")
            PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_dir(path, label):
    global PASS, FAIL
    if os.path.isdir(path):
        print(f"  OK    {label}: {path} ({len(os.listdir(path))} items)")
        PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_import(module, label):
    # Also search HydroCraft python_env for packages
    import sys
    _penv = "/mnt/disk1/Hydrocraft_server/python_env/lib/python3.12/site-packages"
    if _penv not in sys.path:
        sys.path.insert(0, _penv)
    global PASS, FAIL
    try:
        __import__(module)
        print(f"  OK    {label}: import {module}")
        PASS += 1
    except ImportError as e:
        print(f"  FAIL  {label}: {e}")
        print(f"         Fix: pip install {module.split('.')[0]}")
        FAIL += 1

def main():
    global PASS, FAIL
    print(f"{' PREFLIGHT: CWatM ':=^60}")
    print()
    check_dir("/mnt/disk1/Hydrocraft_server/models/CWatM/knowledge_infrastructure/tools", "KI tools directory")

    # Model-specific package check. CWatM is natively Python: run_cwatm.py IS the
    # model. The old code printed "binary path not verified" and counted it as a
    # PASS, so preflight succeeded even when the model could not be imported.
    repo = "/mnt/disk1/Hydrocraft_server/models/CWatM/source/repo"
    check_file(os.path.join(repo, "run_cwatm.py"), "CWatM entry point")
    check_file(os.path.join(repo, "cwatm", "hydrological_modules",
                            "routing_reservoirs", "t5_linux.so"),
               "C++ kinematic-routing library")
    for mod in ("numpy", "netCDF4", "osgeo.gdal", "rasterio", "pandas"):
        check_import(mod, "python dependency")
    if repo not in sys.path:
        sys.path.insert(0, repo)
    check_import("cwatm.management_modules.globals", "CWatM package")
    if not os.environ.get("LD_PRELOAD"):
        print("  INFO  If osgeo raises 'static TLS block', set "
              "LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6 (triplet cwatm_dt_016)")
    # Check diagnostics
    ki_dir = os.path.dirname(os.path.abspath(__file__))
    triplets = os.path.join(ki_dir, "diagnostics", "triplets.yaml")
    if os.path.isfile(triplets):
        print(f"  INFO  Diagnostics available: {triplets}")

    print(f"\n  Results: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL > 0 else 0)

if __name__ == "__main__":
    main()
