#!/usr/bin/env python3
"""
Knowledge Infrastructure -- Validated Tool
==========================================
Tool ID:      assemble_input_file
Stage:        s5_breach_config
Description:  Assemble all DLBreach cards into a complete casename.txt input file.
              Validates that all required cards are present and properly formatted.

              DLBreach reads a single input file with card-based keywords.
              Cards can appear in any order. Comments start with '!'.
              Multiline cards (reservoir curve, inflow, etc.) must have no
              comments or blank lines between the keyword and data lines.

Inputs:
  --casename:         Case name (input file will be casename.txt)
  --output_dir:       Directory to write the input file
  --time_step:        Time step in seconds (0.1-5.0)
  --sim_period:       Simulation period as "start_sec, end_sec"
  --geometry_json:    JSON file from create_dam_geometry tool
  --reservoir_json:   JSON file from create_reservoir_curve tool
  --inflow_json:      JSON file from convert_cama_to_inflow tool
  --breach_json:      JSON file from set_breach_parameters tool
  --extra_cards:      Additional cards as multi-line string

Outputs:
  - JSON with input_file_path, card_count, required_cards_present, validation

Exit codes:
  0 -- success
  1 -- missing required cards
  2 -- card format error
  3 -- assembled file validation failed
"""

import sys
import json
import argparse
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# Cards that MUST be present in the input file
REQUIRED_CARDS = [
    "Time_Step",
    "Simulation_Period",
    "Embankment_Height",
    "Embankment_Crest_Width",
    "Embankment_Upstream_Slope",
    "Embankment_Downstream_Slope",
    "Embankment_Length",
    "Breach_Mode",
    "Noncohesive_or_Cohesive_Sediment",
    "Sediment_Diameter",
    "Sediment_Specific_Gravity",
    "Sediment_Porosity",
    "Sediment_Internal_Friction",
    "Initial_Up&Downstream_WSL",
]

# Cards that should be present but have defaults
RECOMMENDED_CARDS = [
    "Breach_Location",
    "Breach_Manning_n",
    "Upstream_Reservoir",
]


def extract_cards_from_json(json_path, key):
    """Extract card text from a tool output JSON file."""
    with open(json_path) as f:
        data = json.load(f)
    return data.get(key, "")


def check_required_cards(input_text):
    """Check which required cards are present."""
    present = []
    missing = []
    for card in REQUIRED_CARDS:
        # Handle the & character in Initial_Up&Downstream_WSL
        search_card = card.replace("&", "&")
        if search_card in input_text:
            present.append(card)
        else:
            missing.append(card)
    return present, missing


def check_recommended_cards(input_text):
    """Check which recommended cards are present."""
    present = []
    missing = []
    for card in RECOMMENDED_CARDS:
        if card in input_text:
            present.append(card)
        else:
            missing.append(card)
    return present, missing


def count_cards(input_text):
    """Count number of card keywords in the input."""
    count = 0
    for line in input_text.split("\n"):
        stripped = line.strip()
        if stripped and not stripped.startswith("!") and not stripped.startswith("#"):
            # Check if line starts with a keyword (uppercase letter or has underscore)
            first_word = stripped.split()[0] if stripped.split() else ""
            if "_" in first_word or first_word[0:1].isupper():
                count += 1
    return count


def assemble(args):
    """Assemble all sections into a complete input file."""
    sections = []

    # Header comment
    sections.append(f"! DLBreach Input File: {args.casename}")
    sections.append(f"! Generated by HydroCraft DLBreach Knowledge Infrastructure")
    sections.append(f"! =========================================================")
    sections.append("")

    # Time step and simulation period
    sections.append("! --- Time Configuration ---")
    sections.append(f"Time_Step    {args.time_step:.2f}    ! in seconds")
    if args.sim_period:
        # Ensure space after comma: "0,108000" → "0, 108000" (parser needs space-separated)
        sp = args.sim_period.replace(",", ", ").replace(",  ", ", ")
        sections.append(f"Simulation_Period    {sp}    ! in seconds")
    sections.append("")

    # Geometry cards
    if args.geometry_json:
        sections.append("! --- Embankment Geometry ---")
        geo_cards = extract_cards_from_json(args.geometry_json, "geometry_cards")
        if geo_cards:
            sections.append(geo_cards)
        sections.append("")

    # Breach parameter cards
    if args.breach_json:
        sections.append("! --- Breach Parameters ---")
        breach_cards = extract_cards_from_json(args.breach_json, "parameter_cards")
        if breach_cards:
            sections.append(breach_cards)
        sections.append("")

    # Reservoir curve cards
    if args.reservoir_json:
        sections.append("! --- Reservoir Storage Curve ---")
        res_cards = extract_cards_from_json(args.reservoir_json, "reservoir_card")
        if res_cards:
            sections.append(res_cards)
        sections.append("")

    # Inflow hydrograph cards
    if args.inflow_json:
        sections.append("! --- Inflow Hydrograph ---")
        inflow_cards = extract_cards_from_json(args.inflow_json, "inflow_card")
        if inflow_cards:
            sections.append(inflow_cards)
        sections.append("")

    # Downstream channel — REQUIRED by Fortran binary (empty output without it)
    ds_width = getattr(args, 'ds_channel_width', None) or 50.0
    ds_slope = getattr(args, 'ds_channel_slope', None) or 0.005
    ds_manning = getattr(args, 'ds_channel_manning', None) or 0.03
    sections.append(f"Downstream_Channel_Flow_Out         {ds_width}, {ds_slope}, {ds_manning}")
    sections.append("")

    # Extra cards
    if args.extra_cards:
        sections.append("! --- Additional Cards ---")
        sections.append(args.extra_cards)
        sections.append("")

    sections.append("END_PARAMETERS")
    sections.append("")

    return "\n".join(sections)


def main():
    parser = argparse.ArgumentParser(description="Assemble DLBreach input file")
    parser.add_argument("--casename", type=str, required=True, help="Case name")
    parser.add_argument("--output_dir", type=str, required=True, help="Output directory")
    parser.add_argument("--time_step", type=float, default=1.0, help="Time step (seconds)")
    parser.add_argument("--sim_period", type=str, help="Simulation period 'start, end' in seconds")
    parser.add_argument("--geometry_json", type=str, help="JSON from create_dam_geometry")
    parser.add_argument("--reservoir_json", type=str, help="JSON from create_reservoir_curve")
    parser.add_argument("--inflow_json", type=str, help="JSON from convert_cama_to_inflow")
    parser.add_argument("--breach_json", type=str, help="JSON from set_breach_parameters")
    parser.add_argument("--extra_cards", type=str, help="Additional cards text")
    parser.add_argument("--ds_channel_width", type=float, default=50.0, help="Downstream channel width (m)")
    parser.add_argument("--ds_channel_slope", type=float, default=0.005, help="Downstream channel slope (m/m)")
    parser.add_argument("--ds_channel_manning", type=float, default=0.03, help="Downstream channel Manning's n")
    parser.add_argument("--output", type=str, help="Output JSON path (metadata)")
    args = parser.parse_args()

    result = {
        "input_file_path": None,
        "casename": args.casename,
        "card_count": 0,
        "required_present": [],
        "required_missing": [],
        "recommended_missing": [],
        "validation_errors": [],
        "status": "error",
    }

    # Assemble the input file
    input_text = assemble(args)

    # Validate
    req_present, req_missing = check_required_cards(input_text)
    rec_present, rec_missing = check_recommended_cards(input_text)

    result["required_present"] = req_present
    result["required_missing"] = req_missing
    result["recommended_missing"] = rec_missing
    result["card_count"] = count_cards(input_text)

    if req_missing:
        result["validation_errors"].append(f"Missing required cards: {req_missing}")
        logger.warning(f"Missing required cards: {req_missing}")

    if rec_missing:
        logger.info(f"Missing recommended cards (have defaults): {rec_missing}")

    # Write the input file
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    input_path = output_dir / f"{args.casename}.txt"
    input_path.write_text(input_text)

    result["input_file_path"] = str(input_path)
    result["status"] = "success" if not req_missing else "incomplete"

    logger.info(f"Input file written: {input_path} ({result['card_count']} cards)")

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(json.dumps(result, indent=2))

    print(json.dumps(result, indent=2))
    sys.exit(0 if not req_missing else 1)


if __name__ == "__main__":
    main()
