#!/usr/bin/env python3
"""
generate_wflow_toml.py — Generate wflow TOML configuration file.

CRITICAL: wflow v1.0+ uses CSDMS standard names in the TOML configuration.
This is a BREAKING CHANGE from pre-v1.0 where shorter names were used.
Most online examples and tutorials use the OLD format — they will NOT work
with wflow v1.0+.

This tool generates a valid v1.0+ TOML file. If you need pre-v1.0 format,
use --legacy flag.

Usage:
    python generate_wflow_toml.py \
      --config /path/to/wflow_config.yaml \
      --output /path/to/wflow_sbm.toml

    python generate_wflow_toml.py \
      --staticmaps staticmaps.nc \
      --forcing forcing.nc \
      --start_date 2000-01-01 --end_date 2010-12-31 \
      --routing kinematic \
      --output wflow_sbm.toml
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path


def validate_inputs(args):
    """Validate inputs."""
    errors = []

    if args.config and not os.path.exists(args.config):
        errors.append(f"Config not found: {args.config}")

    if not args.config:
        if not args.staticmaps:
            errors.append("--staticmaps required when --config not provided")
        if not args.forcing:
            errors.append("--forcing required when --config not provided")
        if not args.start_date or not args.end_date:
            errors.append("--start_date and --end_date required when --config not provided")

    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)


def generate_toml_content(
    staticmaps_path,
    forcing_path,
    start_date,
    end_date,
    output_dir,
    routing="kinematic",
    timestep=86400,
    sediment=False,
    glacier=False,
    output_grid_nc="output_grid.nc",
    output_scalar_nc="output_scalar.nc",
    outstates_nc="outstates.nc",
    instates_nc="",
    legacy=False,
):
    """Generate the TOML configuration string.

    This generates a valid wflow v1.1.0+ TOML configuration using CSDMS standard
    names. IMPORTANT: wflow v1.1.0 has completely different TOML format from pre-v1.0.
    Key differences:
      - [time] not [calendar]
      - [model] uses double-underscore field names (snow__flag, glacier__flag, etc.)
      - [input] requires basin__local_drain_direction, river_location__mask,
        subbasin_location__count as mandatory fields
      - [input.forcing] uses CSDMS names (atmosphere_water__precipitation_volume_flux, etc.)
      - [input.static] uses CSDMS names for all parameters
      - [state.variables] must list ALL 11 required state variables even for cold start
      - [output.csv.column] uses 'parameter' not 'map'
      - soil_layer__thickness creates maxlayers = n + 1 internally
    """
    lines = []
    lines.append("# wflow_sbm configuration file")
    lines.append(f"# Generated by HydroCraft generate_wflow_toml.py")
    lines.append(f"# Date: {datetime.now().isoformat()}")
    lines.append(f"# IMPORTANT: wflow v1.1.0+ CSDMS standard names format")
    lines.append("")

    lines.append('dir_input = "."')
    lines.append('dir_output = "."')
    lines.append("")

    # --- Time section ---
    lines.append("[time]")
    lines.append(f'starttime = {start_date}T00:00:00')
    lines.append(f'endtime = {end_date}T00:00:00')
    lines.append(f"timestepsecs = {timestep}")
    lines.append("")

    lines.append("[logging]")
    lines.append('loglevel = "info"')
    lines.append("")

    # --- Model section ---
    lines.append("[model]")
    lines.append('type = "sbm"')
    lines.append(f"snow__flag = true")
    lines.append(f"glacier__flag = {'true' if glacier else 'false'}")
    lines.append(f"cold_start__flag = {'false' if instates_nc else 'true'}")
    lines.append("soil_layer__thickness = [100, 300, 1500]")
    lines.append("")

    # --- Input section ---
    lines.append("[input]")
    lines.append(f'path_forcing = "{forcing_path}"')
    lines.append(f'path_static = "{staticmaps_path}"')
    lines.append("")
    lines.append("# Domain definition (mandatory)")
    lines.append('basin__local_drain_direction = "wflow_ldd"')
    lines.append('river_location__mask = "wflow_river"')
    lines.append('subbasin_location__count = "wflow_subcatch"')
    lines.append("")

    # Forcing variables (CSDMS standard names)
    lines.append("[input.forcing]")
    lines.append('atmosphere_water__precipitation_volume_flux = "precip"')
    lines.append('land_surface_water__potential_evaporation_volume_flux = "pet"')
    lines.append('atmosphere_air__temperature = "temp"')
    lines.append("")

    # Static input (CSDMS standard names)
    lines.append("[input.static]")
    lines.append("# Snow parameters")
    lines.append('atmosphere_air__snowfall_temperature_threshold = "tt"')
    lines.append('atmosphere_air__snowfall_temperature_interval = "tti"')
    lines.append('snowpack__melting_temperature_threshold = "ttm"')
    lines.append('snowpack__degree_day_coefficient = "cfmax"')
    lines.append("")
    lines.append("# Soil parameters")
    lines.append("soil_layer_water__brooks_corey_exponent.value = [10.0, 10.0, 10.0, 10.0]")
    lines.append('soil_surface_water__vertical_saturated_hydraulic_conductivity = "KsatVer"')
    lines.append('soil_water__vertical_saturated_hydraulic_conductivity_scale_parameter = "f"')
    lines.append('compacted_soil_surface_water__infiltration_capacity = "InfiltCapPath"')
    lines.append('soil_water__residual_volume_fraction = "theta_r"')
    lines.append('soil_water__saturated_volume_fraction = "theta_s"')
    lines.append('soil_water_saturated_zone_bottom__max_leakage_volume_flux = "MaxLeakage"')
    lines.append('compacted_soil__area_fraction = "PathFrac"')
    lines.append('soil__thickness = "SoilThickness"')
    lines.append('subsurface_water__horizontal_to_vertical_saturated_hydraulic_conductivity_ratio = "KsatHorFrac"')
    lines.append("")
    lines.append("# Vegetation parameters")
    lines.append('vegetation_canopy__gap_fraction = "CanopyGapFraction"')
    lines.append('vegetation_water__storage_capacity = "Cmax"')
    lines.append('vegetation_root__depth = "RootingDepth"')
    lines.append('land_water_covered__area_fraction = "WaterFrac"')
    lines.append("")
    lines.append("# River parameters")
    lines.append('river__length = "RiverLength"')
    lines.append('river_water_flow__manning_n_parameter = "N_River"')
    lines.append('river__slope = "RiverSlope"')
    lines.append('river__width = "RiverWidth"')
    lines.append("")
    lines.append("# Land surface parameters")
    lines.append('land_surface_water_flow__manning_n_parameter = "N"')
    lines.append('land_surface__slope = "Slope"')
    lines.append("")

    # --- State section ---
    lines.append("[state]")
    lines.append(f'path_output = "{outstates_nc}"')
    if instates_nc:
        lines.append(f'path_input = "{instates_nc}"')
    lines.append("")

    # State variable mappings (ALL 11 required even for cold start)
    lines.append("[state.variables]")
    lines.append('snowpack_dry_snow__leq_depth = "snow"')
    lines.append('snowpack_liquid_water__depth = "snowwater"')
    lines.append('vegetation_canopy_water__depth = "canopystorage"')
    lines.append('soil_water_saturated_zone__depth = "satwaterdepth"')
    lines.append('soil_surface__temperature = "tsoil"')
    lines.append('soil_layer_water_unsaturated_zone__depth = "ustorelayerdepth"')
    lines.append('subsurface_water__volume_flow_rate = "ssf"')
    lines.append('land_surface_water__instantaneous_volume_flow_rate = "q_land"')
    lines.append('land_surface_water__depth = "h_land"')
    lines.append('river_water__instantaneous_volume_flow_rate = "q_river"')
    lines.append('river_water__depth = "h_river"')
    lines.append("")

    # --- Output section ---
    lines.append("[output.netcdf_grid]")
    lines.append(f'path = "{output_grid_nc}"')
    lines.append("")

    lines.append("[output.netcdf_grid.variables]")
    lines.append('river_water__volume_flow_rate = "q_river"')
    lines.append("")

    # CSV output
    lines.append("[output.csv]")
    lines.append('path = "output.csv"')
    lines.append("")

    lines.append("[[output.csv.column]]")
    lines.append('header = "Q_outlet"')
    lines.append('parameter = "river_water__volume_flow_rate"')
    lines.append('reducer = "maximum"')
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate wflow TOML configuration file"
    )
    parser.add_argument("--config", type=str, default="",
                        help="HydroCraft wflow_config.yaml")
    parser.add_argument("--staticmaps", type=str, default="staticmaps.nc")
    parser.add_argument("--forcing", type=str, default="forcing.nc")
    parser.add_argument("--start_date", type=str, default="")
    parser.add_argument("--end_date", type=str, default="")
    parser.add_argument("--routing", type=str, default="kinematic",
                        choices=["kinematic", "local_inertial"])
    parser.add_argument("--timestep", type=int, default=86400,
                        help="Timestep in seconds (default: 86400 = daily)")
    parser.add_argument("--sediment", action="store_true")
    parser.add_argument("--glacier", action="store_true")
    parser.add_argument("--instates", type=str, default="",
                        help="Path to initial states NetCDF for warm start")
    parser.add_argument("--output_dir", type=str, default="output")
    parser.add_argument("--legacy", action="store_true",
                        help="Generate pre-v1.0 TOML format")
    parser.add_argument("--output", type=str, required=True)
    args = parser.parse_args()

    validate_inputs(args)

    # Load config if provided
    if args.config:
        import yaml
        with open(args.config) as f:
            config = yaml.safe_load(f)
        staticmaps = config["paths"]["staticmaps"]
        forcing = config["paths"]["forcing_nc"]
        start_date = f"{config['simulation']['start_year']}-01-01"
        end_date = f"{config['simulation']['end_year']}-12-31"
        routing = config["model"]["routing"]
        sediment = config["model"]["sediment"]
        glacier = config["model"]["glacier"]
        output_dir = config["paths"]["output_dir"]
        timestep = config["simulation"]["timestep_seconds"]
    else:
        staticmaps = args.staticmaps
        forcing = args.forcing
        start_date = args.start_date
        end_date = args.end_date
        routing = args.routing
        sediment = args.sediment
        glacier = args.glacier
        output_dir = args.output_dir
        timestep = args.timestep

    content = generate_toml_content(
        staticmaps_path=staticmaps,
        forcing_path=forcing,
        start_date=start_date,
        end_date=end_date,
        output_dir=output_dir,
        routing=routing,
        timestep=timestep,
        sediment=sediment,
        glacier=glacier,
        instates_nc=args.instates,
    )

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(content)

    result = {
        "status": "success",
        "toml_path": args.output,
        "model_type": "wflow_sbm",
        "routing": routing,
        "period": f"{start_date} to {end_date}",
        "timestep_seconds": timestep,
        "sediment": sediment,
        "glacier": glacier,
    }

    print(json.dumps(result, indent=2))
    sys.exit(0)


if __name__ == "__main__":
    main()
