#!/usr/bin/env python3
"""Preflight check for ESMF — auto-generated by KDT v5.0

The ESMF engine on this server is the conda env obs4mips (esmpy + ESMF_RegridWeightGen 8.9.1).
Override with ESMF_PYTHON (interpreter that has esmpy) and ESMF_REGRIDWEIGHTGEN (CLI path).
KI tools (tools/generate_regrid_weights.py) must be run with that interpreter, or with its
bin/ folder on PATH, so they find esmpy / ESMF_RegridWeightGen.
"""
import os, sys, shutil, subprocess

PASS = FAIL = 0
MODEL_NAME = "ESMF"
ESMF_ENV = "KISSPATH_HOME/miniconda3/envs/obs4mips"
# An override set to "" is invalid (it fails below); it does not fall back to the default.
ESMF_PYTHON = os.environ.get("ESMF_PYTHON", os.path.join(ESMF_ENV, "bin", "python"))
ESMF_REGRIDWEIGHTGEN = os.environ.get(
    "ESMF_REGRIDWEIGHTGEN", os.path.join(ESMF_ENV, "bin", "ESMF_RegridWeightGen"))

def check_file(path, label, executable=False):
    global PASS, FAIL
    if os.path.isfile(path):
        if executable and not os.access(path, os.X_OK):
            print(f"  WARN  {label}: exists but not executable: {path}")
            FAIL += 1
        else:
            print(f"  OK    {label}: {path}")
            PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_dir(path, label):
    global PASS, FAIL
    if os.path.isdir(path):
        print(f"  OK    {label}: {path} ({len(os.listdir(path))} items)")
        PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_import(module, label, python=ESMF_PYTHON, timeout=180):
    """Import `module` in the ESMF engine interpreter (not in this preflight's own python)."""
    global PASS, FAIL
    fix = (f"Point ESMF_PYTHON at a python that has {module} (server default: "
           f"{ESMF_ENV}/bin/python); run the KI tools with that python")
    if not (os.path.isfile(python) and os.access(python, os.X_OK)):
        print(f"  FAIL  {label}: interpreter not found/executable: {python}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return
    code = (f"import sys, {module} as m; "
            "print(sys.executable, getattr(m, '__version__', '?'), getattr(m, '__file__', ''))")
    try:
        proc = subprocess.run([python, "-c", code], capture_output=True, text=True,
                              timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"  FAIL  {label}: import {module} in {python} did not finish: {exc}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return
    if proc.returncode == 0:
        print(f"  OK    {label}: import {module} in {python} -> {proc.stdout.strip()}")
        PASS += 1
    else:
        lines = (proc.stderr or proc.stdout).strip().splitlines()
        print(f"  FAIL  {label}: {lines[-1] if lines else 'import failed'} ({python})")
        print(f"         Fix: {fix}")
        FAIL += 1

def check_regridweightgen(path=ESMF_REGRIDWEIGHTGEN, timeout=180):
    """ESMF_RegridWeightGen must start and report its version (no regridding is run)."""
    global PASS, FAIL
    label = "ESMF_RegridWeightGen"
    fix = (f"Point ESMF_REGRIDWEIGHTGEN at a working ESMF_RegridWeightGen (server default: "
           f"{ESMF_ENV}/bin/ESMF_RegridWeightGen); put its folder on PATH when running KI tools")
    if not (os.path.isfile(path) and os.access(path, os.X_OK)):
        print(f"  FAIL  {label}: NOT FOUND or not executable at {path}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return
    try:
        proc = subprocess.run([path, "--version"], capture_output=True, text=True,
                              timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"  FAIL  {label}: --version did not finish ({path}): {exc}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return
    out = proc.stdout + proc.stderr
    version = next((l.split(":", 1)[1].strip() for l in out.splitlines()
                    if l.strip().startswith("ESMF_VERSION_STRING:")), "")
    if proc.returncode == 0 and version:
        print(f"  OK    {label}: {path} (ESMF {version})")
        PASS += 1
    else:
        lines = out.strip().splitlines()
        print(f"  FAIL  {label}: --version rc={proc.returncode}: "
              f"{lines[-1] if lines else 'no output'} ({path})")
        print(f"         Fix: {fix}")
        FAIL += 1

def check_tool_launch_route():
    """FAIL when the KI tools, started the way SKILL.md documents (HydroCraft
    python_env, this process's PATH), would not reach a working ESMF.
    generate_regrid_weights.py uses the first ESMF_RegridWeightGen on PATH and falls
    back to `import esmpy` ONLY when no binary is on PATH (a broken one is not skipped)."""
    global PASS, FAIL
    penv = "KISSPATH_PYTHON_ENV/bin/python"
    fix = (f"run tools/generate_regrid_weights.py with {ESMF_PYTHON} and put "
           f"{os.path.dirname(ESMF_REGRIDWEIGHTGEN)} first on PATH (or fix the KI launcher/SKILL.md to do so)")
    on_path = shutil.which("ESMF_RegridWeightGen")
    if on_path:
        try:
            probe = subprocess.run([on_path, "--version"], capture_output=True, text=True,
                                   timeout=180)
            ok = probe.returncode == 0 and "ESMF_VERSION_STRING:" in probe.stdout + probe.stderr
        except (OSError, subprocess.TimeoutExpired):
            ok = False
        if ok:
            print(f"  OK    tool launch route: ESMF_RegridWeightGen on PATH works: {on_path}")
            PASS += 1
        else:
            print(f"  FAIL  tool launch route: the ESMF_RegridWeightGen first on PATH ({on_path}) "
                  "does not start with --version; KI tools would use it and not fall back to esmpy")
            print(f"         Fix: {fix}")
            FAIL += 1
        return
    esmpy_in_penv = False
    if os.path.isfile(penv):
        try:
            esmpy_in_penv = subprocess.run(
                [penv, "-c",  # same fallback as the tool: import esmpy, else import ESMF
                 "try:\n    import esmpy\nexcept ImportError:\n    import ESMF as esmpy"],
                capture_output=True, timeout=180).returncode == 0
        except (OSError, subprocess.TimeoutExpired):
            esmpy_in_penv = False
    if esmpy_in_penv:
        print(f"  OK    tool launch route: no ESMF_RegridWeightGen on PATH; esmpy (or legacy ESMF) imports in {penv}")
        PASS += 1
    else:
        print(f"  FAIL  tool launch route: KI tools started with {penv} (as SKILL.md lists) find "
              "no ESMF_RegridWeightGen on PATH and cannot import esmpy (or legacy ESMF), so they cannot reach the ESMF checked above")
        print(f"         Fix: {fix}")
        FAIL += 1

def main():
    global PASS, FAIL
    print(f"{' PREFLIGHT: ESMF ':=^60}")
    print()
    check_import("esmpy", "esmpy")
    check_regridweightgen()
    check_tool_launch_route()
    # Check diagnostics
    ki_dir = os.path.dirname(os.path.abspath(__file__))
    triplets = os.path.join(ki_dir, "diagnostics", "triplets.yaml")
    if os.path.isfile(triplets):
        print(f"  INFO  Diagnostics available: {triplets}")

    print(f"\n  Results: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL > 0 else 0)

if __name__ == "__main__":
    main()
