#!/usr/bin/env python3
"""Preflight check for ESMF — auto-generated by KDT v5.0

The ESMF engine on this server is the conda env obs4mips (esmpy + ESMF_RegridWeightGen 8.9.1).
Override with ESMF_PYTHON (interpreter that has esmpy) and ESMF_REGRIDWEIGHTGEN (CLI path).
tools/generate_regrid_weights.py finds them itself (same env vars and defaults), so SKILL.md's
python_env call works; the launch-route check below asks the tool which engine it would use.
"""
import os, sys, shutil, subprocess

PASS = FAIL = 0
MODEL_NAME = "ESMF"
ESMF_ENV = "KISSPATH_HOME/miniconda3/envs/obs4mips"
# An override set to "" is invalid (it fails below); it does not fall back to the default.
ESMF_PYTHON = os.environ.get("ESMF_PYTHON", os.path.join(ESMF_ENV, "bin", "python"))
ESMF_REGRIDWEIGHTGEN = os.environ.get(
    "ESMF_REGRIDWEIGHTGEN", os.path.join(ESMF_ENV, "bin", "ESMF_RegridWeightGen"))

def check_file(path, label, executable=False):
    global PASS, FAIL
    if os.path.isfile(path):
        if executable and not os.access(path, os.X_OK):
            print(f"  WARN  {label}: exists but not executable: {path}")
            FAIL += 1
        else:
            print(f"  OK    {label}: {path}")
            PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_dir(path, label):
    global PASS, FAIL
    if os.path.isdir(path):
        print(f"  OK    {label}: {path} ({len(os.listdir(path))} items)")
        PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_import(module, label, python=ESMF_PYTHON, timeout=180):
    """Import `module` in the ESMF engine interpreter (not in this preflight's own python)."""
    global PASS, FAIL
    fix = (f"Point ESMF_PYTHON at a python that has {module} (server default: "
           f"{ESMF_ENV}/bin/python); run the KI tools with that python")
    if not (os.path.isfile(python) and os.access(python, os.X_OK)):
        print(f"  FAIL  {label}: interpreter not found/executable: {python}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return
    code = (f"import sys, {module} as m; "
            "print(sys.executable, getattr(m, '__version__', '?'), getattr(m, '__file__', ''))")
    try:
        proc = subprocess.run([python, "-c", code], capture_output=True, text=True,
                              timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"  FAIL  {label}: import {module} in {python} did not finish: {exc}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return
    if proc.returncode == 0:
        print(f"  OK    {label}: import {module} in {python} -> {proc.stdout.strip()}")
        PASS += 1
    else:
        lines = (proc.stderr or proc.stdout).strip().splitlines()
        print(f"  FAIL  {label}: {lines[-1] if lines else 'import failed'} ({python})")
        print(f"         Fix: {fix}")
        FAIL += 1

def check_regridweightgen(path=ESMF_REGRIDWEIGHTGEN, timeout=180):
    """ESMF_RegridWeightGen must start and report its version (no regridding is run)."""
    global PASS, FAIL
    label = "ESMF_RegridWeightGen"
    fix = (f"Point ESMF_REGRIDWEIGHTGEN at a working ESMF_RegridWeightGen (server default: "
           f"{ESMF_ENV}/bin/ESMF_RegridWeightGen); put its folder on PATH when running KI tools")
    if not (os.path.isfile(path) and os.access(path, os.X_OK)):
        print(f"  FAIL  {label}: NOT FOUND or not executable at {path}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return
    try:
        proc = subprocess.run([path, "--version"], capture_output=True, text=True,
                              timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"  FAIL  {label}: --version did not finish ({path}): {exc}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return
    out = proc.stdout + proc.stderr
    version = next((l.split(":", 1)[1].strip() for l in out.splitlines()
                    if l.strip().startswith("ESMF_VERSION_STRING:")), "")
    if proc.returncode == 0 and version:
        print(f"  OK    {label}: {path} (ESMF {version})")
        PASS += 1
    else:
        lines = out.strip().splitlines()
        print(f"  FAIL  {label}: --version rc={proc.returncode}: "
              f"{lines[-1] if lines else 'no output'} ({path})")
        print(f"         Fix: {fix}")
        FAIL += 1

def check_tool_launch_route():
    """FAIL when the KI tool, started the way SKILL.md documents (HydroCraft python_env,
    this process's environment), would not reach a working ESMF. The tool resolves the
    engine itself (tools/generate_regrid_weights.py: binary --regridweightgen ->
    $ESMF_REGRIDWEIGHTGEN -> server default -> PATH; ESMPy --esmf-python -> $ESMF_PYTHON ->
    server default -> its own python), so ask it: `--check-engine` runs the same lookup and
    re-launch as a real run and probes the engine. Both routes are checked."""
    global PASS, FAIL
    penv = "KISSPATH_PYTHON_ENV/bin/python"
    tool = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools",
                        "generate_regrid_weights.py")
    fix = ("set ESMF_REGRIDWEIGHTGEN / ESMF_PYTHON to a working ESMF (server default: "
           f"{ESMF_ENV}), or pass --regridweightgen / --esmf-python to the tool")
    for label, extra in (("ESMF_RegridWeightGen route", []), ("ESMPy route", ["--use-esmpy"])):
        cmd = [penv, tool, "--check-engine"] + extra
        try:
            proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        except (OSError, subprocess.TimeoutExpired) as exc:
            print(f"  FAIL  tool launch route ({label}): {' '.join(cmd)} did not finish: {exc}")
            print(f"         Fix: {fix}")
            FAIL += 1
            continue
        lines = proc.stdout.strip().splitlines()
        detail = lines[-1] if lines else (proc.stderr.strip().splitlines() or ["no output"])[-1]
        if proc.returncode == 0:
            print(f"  OK    tool launch route ({label}): python_env tools/generate_regrid_weights.py -> {detail}")
            PASS += 1
        else:
            print(f"  FAIL  tool launch route ({label}): python_env tools/generate_regrid_weights.py "
                  f"--check-engine rc={proc.returncode}: {detail}")
            print(f"         Fix: {fix}")
            FAIL += 1

def main():
    global PASS, FAIL
    print(f"{' PREFLIGHT: ESMF ':=^60}")
    print()
    check_import("esmpy", "esmpy")
    check_regridweightgen()
    check_tool_launch_route()
    # Check diagnostics
    ki_dir = os.path.dirname(os.path.abspath(__file__))
    triplets = os.path.join(ki_dir, "diagnostics", "triplets.yaml")
    if os.path.isfile(triplets):
        print(f"  INFO  Diagnostics available: {triplets}")

    print(f"\n  Results: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL > 0 else 0)

if __name__ == "__main__":
    main()
