#!/usr/bin/env python3
"""generate_control_file.py — Generate mizuRoute control file.

Creates the control file that configures mizuRoute: routing method, input/output
paths, variable name mappings, time settings, and lake routing options.

mizuRoute control file format is key-value pairs: <variable_name>  <value>
Lines starting with ! are comments.

Routing methods:
  0 = IRF (Impulse Response Function) — unit hydrograph convolution per reach
  1 = KWT (Kinematic Wave Tracking) — Lagrangian wave tracking
  2 = KWE (Kinematic Wave Euler) — fixed-grid finite difference
  3 = MC  (Muskingum-Cunge) — storage routing with geometry-based params
  4 = DW  (Diffusive Wave) — includes backwater effects

Usage:
    python generate_control_file.py \\
        --basin_name chaohe \\
        --network_nc outputs/<run>/mizuroute_input/network_topology.nc \\
        --runoff_nc outputs/<run>/mizuroute_input/runoff.nc \\
        --remap_nc outputs/<run>/mizuroute_input/remap_weights.nc \\
        --output_dir outputs/<run>/mizuroute_output \\
        --output outputs/<run>/mizuroute_input/chaohe.control \\
        --route_opt 0 \\
        --start_date 2000-01-01 --end_date 2010-12-31 \\
        --dt 3600
"""
import argparse
import json
import os
import sys
from datetime import datetime
sys.path.insert(0, "/home/server/knowledge-dissection-toolkit/auto_dissect")
from ki_tools_common.units import CMFD_PRECIP_KGM2S_TO_MMDAY


CONTROL_TEMPLATE = """! ====================================================================
! mizuRoute control file - {basin_name}
! Generated by generate_control_file.py (HydroCraft)
! {timestamp}
! ====================================================================
! --- Directory and file paths ---
<ancil_dir>             {ancil_dir}                           ! ancillary data directory
<input_dir>             {input_dir}                           ! input directory
<output_dir>            {output_dir}                          ! output directory
! --- Case and file names ---
<case_name>             {basin_name}                          ! simulation case name
<fname_ntopOld>         {network_filename}                    ! network topology file
<fname_qsim>            {runoff_filename}                     ! runoff input file
<param_nml>             param.nml                              ! parameter namelist file
! --- Spatial remapping ---
<is_remap>              {is_remap}                            ! use spatial remapping
<fname_remap>           {remap_filename}                      ! remap weights file
<vname_hruid_in_remap>  HRUid                                 ! HRU ID in remap file
<vname_num_qhru>        num_qhru                              ! number of overlapping grid cells per HRU
<vname_weight>          weight                                ! areal weight of overlapping grid cells
<vname_i_index>         i_index                               ! x (lon) grid index in remap
<vname_j_index>         j_index                               ! y (lat) grid index in remap
<dname_hru_remap>       polyid                                ! HRU dimension in remap
<dname_data_remap>      data                                  ! data dimension in remap
! --- Variable name mapping (network topology) ---
! NOTE: These names MUST match the variables in network_topology.nc exactly.
! The validated Bengbu run uses: seg_id, tosegment, seg_length, seg_slope, hru_id, hru_area, hru_seg_id
<varname_HRUid>         hru_id                                ! HRU id variable
<varname_segId>         seg_id                                ! segment id variable
<varname_downSegId>     tosegment                             ! downstream segment variable
<varname_length>        seg_length                            ! reach length variable
<varname_slope>         seg_slope                             ! reach slope variable
<varname_area>          hru_area                              ! HRU area variable
<varname_hruSegId>      hru_seg_id                            ! HRU-segment mapping
! --- Variable name mapping (runoff input) ---
<vname_qsim>            RUNOFF                                ! runoff variable name
<vname_time>            time                                  ! time variable name
<units_qsim>            mm/s                                  ! runoff units
<dt_qsim>               {dt_qsim}                             ! runoff timestep seconds
<dt_ro>                 {dt_qsim}                             ! runoff data timestep seconds
! --- Dimension names (runoff input) ---
<dname_xlon>            lon                                   ! x dimension name
<dname_ylat>            lat                                   ! y dimension name
<dname_time>            time                                  ! time dimension name
! --- Time settings ---
<sim_start>             {start_date}                          ! simulation start
<sim_end>               {end_date}                            ! simulation end
<newFileFrequency>      yearly                                ! output file frequency
! --- Routing method ---
! route_opt: 0=accumRunoff, 1=IRF, 2=KWT, 3=KWE, 4=MC, 5=DW
<route_opt>             {route_opt}                           ! routing method
<IRFroutedRunoff>       {irf_output}                          ! IRF routed output
<doesBasinRoute>        {does_basin_route}                    ! basin IRF routing
! --- Topology/geometry computation ---
<hydGeometryOption>     1                                     ! compute channel geometry
<topoNetworkOption>     1                                     ! compute network topology
<computeReachList>      1                                     ! compute reach processing list
! --- Lake/Reservoir routing ---
<is_lake_sim>           {is_lake_sim}                         ! lake simulation
! --- Output control ---
<desireId>              -9999                                 ! reach ID for debug output
<outputFrequency>       daily                                 ! output frequency
<KWTroutedRunoff>       T                                     ! KWT routed output
<instRunoff>            T                                     ! instantaneous runoff
<dlayRunoff>            T                                     ! delayed runoff
<sumUpstreamRunoff>     T                                     ! accumulated upstream runoff
! --- Restart ---
<restart_write>         never                                 ! restart frequency
<restart_dir>           {output_dir}                          ! restart directory
"""


def validate_inputs(args):
    errors = []
    if not os.path.isfile(args.network_nc):
        errors.append(f"Network NC not found: {args.network_nc}")
    if not os.path.isfile(args.runoff_nc):
        errors.append(f"Runoff NC not found: {args.runoff_nc}")
    if args.remap_nc and not os.path.isfile(args.remap_nc):
        errors.append(f"Remap NC not found: {args.remap_nc}")
    if args.route_opt not in range(6):
        errors.append(f"route_opt must be 0-5 (0=accum,1=IRF,2=KWT,3=KWE,4=MC,5=DW), got {args.route_opt}")
    if args.dt < 1:
        errors.append(f"dt must be positive, got {args.dt}")
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return False
    return True


def process(args):
    # Determine directories and filenames
    ancil_dir = os.path.dirname(os.path.abspath(args.network_nc)) + '/'
    input_dir = os.path.dirname(os.path.abspath(args.runoff_nc)) + '/'
    output_dir = os.path.abspath(args.output_dir) + '/'

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.dirname(args.output), exist_ok=True)

    is_remap = '.True.' if args.remap_nc else '.False.'
    remap_filename = os.path.basename(args.remap_nc) if args.remap_nc else 'none'

    # Determine dt_qsim from runoff timestep
    import netCDF4 as nc
    with nc.Dataset(args.runoff_nc, 'r') as ds:
        time_var = ds.variables['time']
        if len(time_var) > 1:
            dt_days = float(time_var[1] - time_var[0])
            dt_qsim = int(dt_days * CMFD_PRECIP_KGM2S_TO_MMDAY)
        else:
            dt_qsim = 86400  # assume daily

    # Basin IRF: apply hillslope delay before reach routing
    does_basin_route = 1 if args.basin_irf else 0

    # Lake simulation
    is_lake_sim = '.True.' if args.enable_lakes else '.False.'

    # Enable IRF output if using IRF routing
    irf_output = 'T' if args.route_opt == 1 else 'F'

    control_content = CONTROL_TEMPLATE.format(
        basin_name=args.basin_name,
        timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        ancil_dir=ancil_dir,
        input_dir=input_dir,
        output_dir=output_dir,
        network_filename=os.path.basename(args.network_nc),
        runoff_filename=os.path.basename(args.runoff_nc),
        is_remap=is_remap,
        remap_filename=remap_filename,
        start_date=args.start_date,
        end_date=args.end_date,
        dt=args.dt,
        dt_qsim=dt_qsim,
        route_opt=args.route_opt,
        irf_output=irf_output,
        does_basin_route=does_basin_route,
        is_lake_sim=is_lake_sim,
    )

    with open(args.output, 'w') as f:
        f.write(control_content)

    # Check path lengths (Fortran CHARACTER truncation, dt_m017)
    long_paths = []
    for p in [ancil_dir, input_dir, output_dir]:
        if len(p) > 120:
            long_paths.append(p)

    if long_paths:
        print(f"WARNING: {len(long_paths)} paths exceed 120 chars (Fortran truncation risk, dt_m017)")
        for p in long_paths:
            print(f"  {len(p)} chars: {p}")

    route_names = {0: 'accumRunoff', 1: 'IRF', 2: 'KWT', 3: 'KWE', 4: 'MC', 5: 'DW'}

    return {
        'output_file': args.output,
        'routing_method': route_names.get(args.route_opt, str(args.route_opt)),
        'dt_seconds': args.dt,
        'dt_qsim_seconds': dt_qsim,
        'period': f'{args.start_date} to {args.end_date}',
        'is_remap': args.remap_nc is not None,
        'basin_irf': args.basin_irf,
        'enable_lakes': args.enable_lakes,
        'long_paths': len(long_paths),
    }


def main():
    parser = argparse.ArgumentParser(description='Generate mizuRoute control file')
    parser.add_argument('--basin_name', required=True, help='Basin name')
    parser.add_argument('--network_nc', required=True, help='Network topology NetCDF')
    parser.add_argument('--runoff_nc', required=True, help='Runoff input NetCDF')
    parser.add_argument('--remap_nc', default=None, help='Remap weights NetCDF')
    parser.add_argument('--output_dir', required=True, help='mizuRoute output directory')
    parser.add_argument('--output', required=True, help='Output control file path')
    parser.add_argument('--route_opt', type=int, default=1,
                       help='Routing method: 0=accumRunoff, 1=IRF, 2=KWT, 3=KWE, 4=MC, 5=DW')
    parser.add_argument('--start_date', required=True, help='Start date YYYY-MM-DD')
    parser.add_argument('--end_date', required=True, help='End date YYYY-MM-DD')
    parser.add_argument('--dt', type=int, default=3600,
                       help='Routing timestep in seconds (default: 3600)')
    parser.add_argument('--basin_irf', action='store_true',
                       help='Apply basin (hillslope) IRF before reach routing')
    parser.add_argument('--enable_lakes', action='store_true',
                       help='Enable lake/reservoir routing')

    args = parser.parse_args()

    if not validate_inputs(args):
        sys.exit(1)

    try:
        result = process(args)
        print(json.dumps(result, indent=2))
        print(f"\nSUCCESS: Control file written to {args.output}")
    except Exception as e:
        print(f"PROCESSING ERROR: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(2)


if __name__ == '__main__':
    main()
