#!/usr/bin/env python3
"""Preflight check for SimFire — auto-generated by KDT v5.0"""
import sysconfig
import os, sys, shutil

PASS = FAIL = 0
MODEL_NAME = "SimFire"

def check_file(path, label, executable=False):
    global PASS, FAIL
    if os.path.isfile(path):
        if executable and not os.access(path, os.X_OK):
            print(f"  WARN  {label}: exists but not executable: {path}")
            FAIL += 1
        else:
            print(f"  OK    {label}: {path}")
            PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_dir(path, label):
    global PASS, FAIL
    if os.path.isdir(path):
        print(f"  OK    {label}: {path} ({len(os.listdir(path))} items)")
        PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_import(module, label):
    # NOTE 2026-08-09: this used to sys.path.INSERT(0) the shared HydroCraft
    # python_env in front of everything, which SHADOWS the SimFire venv with a
    # different, older dependency set — every import then failed with
    #   ImportError: cannot import name 'Sequence' from 'collections'
    # i.e. the preflight reported the whole stack broken while the venv was
    # fine. Append instead, so the venv always wins.
    import sys
    _penv = "KISSPATH_PYTHON_ENV/lib/python3.12/site-packages"
    if _penv not in sys.path:
        sys.path.append(_penv)
    global PASS, FAIL
    try:
        __import__(module)
        print(f"  OK    {label}: import {module}")
        PASS += 1
    except ImportError as e:
        print(f"  FAIL  {label}: {e}")
        print(f"         Fix: pip install {module.split('.')[0]}")
        FAIL += 1

def main():
    global PASS, FAIL
    print(f"{' PREFLIGHT: SimFire ':=^60}")
    print()
    # SimFire lives in the dissection venv, not the shared HydroCraft python_env.
    # NOTE 2026-08-09: this file previously did not PARSE — an orphan indented
    # print() on the line after sys.path.insert raised IndentationError, so
    # `python preflight_check.py` (which SKILL.md tells you to run FIRST) always
    # died before printing anything. Rebuilt as a real check.
    import sys
    venv_sp = (sysconfig.get_paths()["purelib"])
    if venv_sp not in sys.path:
        sys.path.insert(0, venv_sp)

    check_dir(venv_sp, "SimFire venv site-packages")
    check_import("simfire.sim.simulation", "SimFire package")
    # Hard runtime deps that are NOT in the venv as shipped and that the
    # operational path needs (verified 2026-08-09):
    #   rasterio  — georeferencing the LandFire raster for perimeter scoring
    #   xarray    — imported eagerly by ki_tools_common/__init__
    #   zarr>=3,<3.2 — geotiff -> tifffile.aszarr; zarr<3 AND zarr>=3.2 both
    #                  raise "zarr X < 3 is not supported" (3.2 dropped
    #                  zarr.core.chunk_grids.RegularChunkGrid)
    check_import("rasterio", "rasterio (LandFire georeferencing)")
    check_import("xarray", "xarray (ki_tools_common import chain)")
    check_import("geopandas", "geopandas (MTBS perimeters)")
    try:
        import zarr
        from zarr.core.chunk_grids import RegularChunkGrid  # noqa: F401
        print(f"  OK    zarr {zarr.__version__} compatible with tifffile.aszarr")
        PASS += 1
    except Exception as exc:
        print(f"  FAIL  zarr/tifffile incompatibility: {exc}")
        print("         Fix: pip install 'zarr>=3,<3.2'")
        FAIL += 1

    check_file(
        "KISSPATH_OBS/fire_perimeters/mtbs/"
        "mtbs_perims/mtbs_perims_DD.shp",
        "MTBS fire perimeters (validation obs)",
    )

    # LandFire Product Service v2 (the legacy GPServer endpoint is retired).
    try:
        import requests
        s = requests.Session()
        s.trust_env = False   # lfps.usgs.gov fails TLS through the proxy
        r = s.get("https://lfps.usgs.gov/api/products", timeout=60)
        n = len(r.json().get("products", []))
        print(f"  OK    LFPS v2 reachable ({n} products)")
        PASS += 1
    except Exception as exc:
        print(f"  FAIL  LFPS v2 unreachable: {exc}")
        print("         Operational terrain/fuel cannot be downloaded. See dt_020.")
        FAIL += 1

    # Check diagnostics
    ki_dir = os.path.dirname(os.path.abspath(__file__))
    triplets = os.path.join(ki_dir, "diagnostics", "triplets.yaml")
    if os.path.isfile(triplets):
        print(f"  INFO  Diagnostics available: {triplets}")

    print(f"\n  Results: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL > 0 else 0)

if __name__ == "__main__":
    main()
