#!/usr/bin/env python3
"""Preflight check for BMI — auto-generated by KDT v5.0"""
import os, sys, shutil, subprocess

PASS = FAIL = 0
MODEL_NAME = "BMI"

# Shared HydroCraft Python (runs the KI tools; has bmipy + numpy).
HYDRO_PYTHON = "KISSPATH_PYTHON_ENV/bin/python"
# Reference BMI model BmiHeat (package `heat`, from csdms/bmi-example-python) is
# installed only in this venv. BMI_HEAT_PYTHON selects which interpreter this
# preflight checks (same name the official test case uses); it does not change
# what other tools run with. A bad override fails; there is no silent fallback.
HEAT_PYTHON_DEFAULT = "KISSPATH_INTERNAL_NOT_SHIPPED/auto_dissect/_work/BMI/venv/bin/python"
HEAT_PYTHON = os.environ.get("BMI_HEAT_PYTHON") or HEAT_PYTHON_DEFAULT
PROBE_TIMEOUT = 180

def check_file(path, label, executable=False):
    global PASS, FAIL
    if os.path.isfile(path):
        if executable and not os.access(path, os.X_OK):
            print(f"  WARN  {label}: exists but not executable: {path}")
            FAIL += 1
        else:
            print(f"  OK    {label}: {path}")
            PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_dir(path, label):
    global PASS, FAIL
    if os.path.isdir(path):
        print(f"  OK    {label}: {path} ({len(os.listdir(path))} items)")
        PASS += 1
    else:
        print(f"  FAIL  {label}: NOT FOUND at {path}")
        FAIL += 1

def check_import(module, label):
    # Also search HydroCraft python_env for packages
    import sys
    _penv = "KISSPATH_PYTHON_ENV/lib/python3.12/site-packages"
    if _penv not in sys.path:
        sys.path.insert(0, _penv)
    global PASS, FAIL
    try:
        __import__(module)
        print(f"  OK    {label}: import {module}")
        PASS += 1
    except ImportError as e:
        print(f"  FAIL  {label}: {e}")
        print(f"         Fix: pip install {module.split('.')[0]}")
        FAIL += 1

def check_python_probe(python, code, label, fix):
    """Run a tiny import probe in a given interpreter (no model run)."""
    global PASS, FAIL
    if not (os.path.isfile(python) and os.access(python, os.X_OK)):
        print(f"  FAIL  {label}: interpreter not found or not executable: {python}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return False
    try:
        proc = subprocess.run([python, "-B", "-c", code], capture_output=True,
                              text=True, timeout=PROBE_TIMEOUT)
    except subprocess.TimeoutExpired:
        print(f"  FAIL  {label}: probe did not finish within {PROBE_TIMEOUT}s in {python}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return False
    except OSError as e:
        print(f"  FAIL  {label}: cannot start {python}: {e}")
        print(f"         Fix: {fix}")
        FAIL += 1
        return False
    if proc.returncode == 0:
        out = proc.stdout.strip().splitlines()
        print(f"  OK    {label}: {python}" + (f" -> {out[-1]}" if out else ""))
        PASS += 1
        return True
    detail = (proc.stderr or proc.stdout).strip().splitlines()
    print(f"  FAIL  {label}: {detail[-1] if detail else 'exit ' + str(proc.returncode)} ({python})")
    print(f"         Fix: {fix}")
    FAIL += 1
    return False

def main():
    global PASS, FAIL
    print(f"{' PREFLIGHT: BMI ':=^60}")
    print()
    check_import("bmipy", "bmipy")
    check_python_probe(
        HYDRO_PYTHON,
        "import bmipy, numpy; print('bmipy', getattr(bmipy, '__version__', '?'))",
        "bmipy + numpy in HydroCraft Python",
        f"{HYDRO_PYTHON} -m pip install bmipy numpy",
    )
    print(f"  INFO  BmiHeat engine Python: {HEAT_PYTHON}"
          + ("" if HEAT_PYTHON == HEAT_PYTHON_DEFAULT else " (from BMI_HEAT_PYTHON)"))
    heat_ok = check_python_probe(
        HEAT_PYTHON,
        "import bmipy, numpy\n"
        "from heat.bmi_heat import BmiHeat\n"
        "if not issubclass(BmiHeat, bmipy.Bmi):\n"
        "    raise SystemExit('heat.bmi_heat.BmiHeat is not a bmipy.Bmi subclass')\n"
        "print('BmiHeat:', BmiHeat().get_component_name())",
        "reference model heat.bmi_heat.BmiHeat (bmipy.Bmi)",
        f"Install bmi-heat from https://github.com/csdms/bmi-example-python with `{HEAT_PYTHON} -m pip install <repo>` "
        f"(server default venv: {HEAT_PYTHON_DEFAULT}), or set BMI_HEAT_PYTHON to a Python that has it. "
        "Note: BMI_HEAT_PYTHON only selects what this preflight checks; tools must be run with that same Python.",
    )
    heat_dir_probe = os.path.join(os.path.dirname(os.path.dirname(HEAT_PYTHON)), "lib")
    for root, dirs, _files in os.walk(heat_dir_probe):
        if os.path.basename(root) == "site-packages":
            heat_pkg = os.path.join(root, "heat")
            if os.path.isdir(heat_pkg) and not os.path.isfile(os.path.join(heat_pkg, "__init__.py")):
                print(f"  INFO  {heat_pkg}/__init__.py is missing: `from heat import BmiHeat` fails; "
                      "import `heat.bmi_heat` directly"
                      + (" (that import works, see check above)" if heat_ok else ""))
            dirs[:] = []
    # Check diagnostics
    ki_dir = os.path.dirname(os.path.abspath(__file__))
    triplets = os.path.join(ki_dir, "diagnostics", "triplets.yaml")
    if os.path.isfile(triplets):
        print(f"  INFO  Diagnostics available: {triplets}")

    print(f"\n  Results: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL > 0 else 0)

if __name__ == "__main__":
    main()
