#!/usr/bin/env python3
"""
generate_site_ini.py
Generate a BIOME-BGC .ini initialization file from structured inputs.

CRITICAL: The .ini file is parsed by KEYWORD + sequential scan_value() calls.
Each value is read in a fixed order AFTER its section keyword. Missing or
extra lines shift all subsequent parameters, causing SILENT errors.

This tool generates .ini files using the exact keyword-section format expected
by BIOME-BGC 4.2 (pointbgc/ini.c, met_init.c, restart_init.c, time_init.c,
scc_init.c, co2_init.c, sitec_init.c, ndep_init.c, epc_init.c, state_init.c,
output_init.c, output_ctrl.c).

Usage:
    python generate_site_ini.py \\
        --met_file metdata/site.mtc43 \\
        --epc_file epc/enf.epc \\
        --output_prefix outputs/test \\
        --lat 46.8 --elevation 977 \\
        --soil_depth 1.0 --sand 30 --silt 50 --clay 20 \\
        --start_year 2000 --n_met_years 10 \\
        --mode normal \\
        --output site.ini

Exit codes: 0=success, 1=input error, 2=processing error, 3=output error
"""

import sys
import os
import json
import argparse
from pathlib import Path

# Add lib to path
LIB_DIR = os.path.join(os.path.dirname(__file__), '..', 'lib')
sys.path.insert(0, LIB_DIR)
from bgc_utils import STANDARD_DAILY_OUTPUT, STANDARD_ANNUAL_OUTPUT


def validate_inputs(args):
    """Validate all input parameters."""
    errors = []

    if not (-90.0 <= args.lat <= 90.0):
        errors.append(f"Latitude {args.lat} out of range [-90, 90]")
    if args.elevation < -500 or args.elevation > 9000:
        errors.append(f"Elevation {args.elevation}m out of range [-500, 9000]")
    if args.soil_depth <= 0 or args.soil_depth > 10:
        errors.append(f"Soil depth {args.soil_depth}m out of range (0, 10]")
    if args.sand < 0 or args.sand > 100:
        errors.append(f"Sand {args.sand}% out of range [0, 100]")
    if args.silt < 0 or args.silt > 100:
        errors.append(f"Silt {args.silt}% out of range [0, 100]")
    if args.clay < 0 or args.clay > 100:
        errors.append(f"Clay {args.clay}% out of range [0, 100]")
    total_tex = args.sand + args.silt + args.clay
    if abs(total_tex - 100.0) > 1.0:
        errors.append(f"Sand+silt+clay={total_tex}%, must sum to 100%")
    if args.n_met_years < 1:
        errors.append(f"n_met_years must be >= 1, got {args.n_met_years}")
    if args.mode not in ("spinup", "normal"):
        errors.append(f"mode must be 'spinup' or 'normal', got '{args.mode}'")
    if args.co2_ppm < 100 or args.co2_ppm > 1500:
        errors.append(f"CO2 {args.co2_ppm} ppm out of range [100, 1500]")
    if args.ndep < 0 or args.ndep > 0.1:
        errors.append(f"N deposition {args.ndep} kgN/m2/yr out of range [0, 0.1]")

    return errors


def generate_ini(args) -> str:
    """
    Generate the .ini file content as a string.
    Follows the exact section order parsed by BIOME-BGC 4.2 pointbgc/ini.c.
    """
    is_spinup = (args.mode == "spinup")
    n_sim_years = args.n_met_years if not is_spinup else args.n_met_years
    restart_file = args.restart_file if args.restart_file else f"restart/{Path(args.output_prefix).stem}.endpoint"

    lines = []
    lines.append(f"Biome-BGC v4.2 initialization file (generated by HydroCraft)")
    lines.append("")

    # MET_INPUT section
    lines.append("MET_INPUT     (keyword) start of meteorology file control block")
    lines.append(f"{args.met_file}  meteorology input filename")
    lines.append(f"{args.met_header_lines}             (int)     header lines in met file")
    lines.append("")

    # RESTART section
    lines.append("RESTART       (keyword) start of restart control block")
    read_restart = 1 if (not is_spinup and args.read_restart) else 0
    write_restart = 1 if is_spinup or args.write_restart else 0
    lines.append(f"{read_restart}             (flag)    1 = read restart file     0 = don't read restart file")
    lines.append(f"{write_restart}             (flag)    1 = write restart file    0 = don't write restart file")
    lines.append(f"1             (flag)    1 = use restart metyear   0 = reset metyear")
    lines.append(f"{restart_file}    input restart filename")
    lines.append(f"{restart_file}    output restart filename")
    lines.append("")

    # TIME_DEFINE section
    lines.append("TIME_DEFINE   (keyword - do not remove)")
    lines.append(f"{args.n_met_years}            (int)       number of meteorological data years")
    lines.append(f"{n_sim_years}            (int)       number of simulation years")
    lines.append(f"{args.start_year}          (int)       first simulation year")
    spinup_flag = 1 if is_spinup else 0
    lines.append(f"{spinup_flag}             (flag)      1 = spinup simulation    0 = normal simulation")
    lines.append(f"{args.max_spinup_years}          (int)       maximum number of spinup years (if spinup simulation)")
    lines.append("")

    # CLIM_CHANGE section
    lines.append("CLIM_CHANGE   (keyword - do not remove)")
    lines.append(f"0.0           (deg C)   offset for Tmax")
    lines.append(f"0.0           (deg C)   offset for Tmin")
    lines.append(f"1.0           (DIM)     multiplier for Prcp")
    lines.append(f"1.0           (DIM)     multiplier for VPD")
    lines.append(f"1.0           (DIM)     multiplier for shortwave radiation")
    lines.append("")

    # CO2_CONTROL section
    co2_flag = 0  # constant
    co2_file = "co2/co2.txt"
    if args.co2_file:
        if args.co2_vary:
            co2_flag = 1  # vary with file
        else:
            co2_flag = 2  # constant, file for Ndep
        co2_file = args.co2_file
    lines.append("CO2_CONTROL   (keyword - do not remove)")
    lines.append(f"{co2_flag}             (flag)    0=constant 1=vary with file 2=constant, file for Ndep")
    lines.append(f"{args.co2_ppm:.3f}       (ppm)     constant atmospheric CO2 concentration")
    lines.append(f"{co2_file}   (file)    annual variable CO2 filename")
    lines.append("")

    # SITE section
    lines.append("SITE          (keyword) start of site physical constants block")
    lines.append(f"{args.soil_depth:.1f}           (m)       effective soil depth (corrected for rock fraction)")
    lines.append(f"{args.sand:.1f}          (%)       sand percentage by volume in rock-free soil")
    lines.append(f"{args.silt:.1f}          (%)       silt percentage by volume in rock-free soil")
    lines.append(f"{args.clay:.1f}          (%)       clay percentage by volume in rock-free soil")
    lines.append(f"{args.elevation:.1f}         (m)       site elevation")
    lines.append(f"{args.lat:.1f}          (degrees) site latitude (- for S.Hem.)")
    lines.append(f"{args.albedo:.2f}          (DIM)     site shortwave albedo")
    lines.append(f"{args.ndep}        (kgN/m2/yr) wet+dry atmospheric deposition of N")
    lines.append(f"{args.nfix}        (kgN/m2/yr) symbiotic+asymbiotic fixation of N")
    lines.append("")

    # RAMP_NDEP section
    lines.append("RAMP_NDEP     (keyword - do not remove)")
    lines.append(f"0             (flag) do a ramped N-deposition run? 0=no, 1=yes")
    lines.append(f"2099          (int)  reference year for industrial N deposition")
    lines.append(f"{args.ndep}        (kgN/m2/yr) industrial N deposition value")
    lines.append("")

    # EPC_FILE section
    lines.append("EPC_FILE      (keyword - do not remove)")
    lines.append(f"{args.epc_file}   (file) ecophysiological constants")
    lines.append("")

    # W_STATE section
    lines.append("W_STATE       (keyword) start of water state variable initialization block")
    lines.append(f"{args.init_snoww:.1f}           (kg/m2)   water stored in snowpack")
    lines.append(f"{args.init_soilw:.2f}           (DIM)     initial soil water as a proportion of saturation")
    lines.append("")

    # C_STATE section
    lines.append("C_STATE       (keyword) start of carbon state variable initialization block")
    lines.append(f"0.001         (kgC/m2)  first-year maximum leaf carbon")
    lines.append(f"0.0           (kgC/m2)  first-year maximum stem carbon")
    lines.append(f"0.0           (kgC/m2)  coarse woody debris carbon")
    lines.append(f"0.0           (kgC/m2)  litter carbon, labile pool")
    lines.append(f"0.0           (kgC/m2)  litter carbon, unshielded cellulose pool")
    lines.append(f"0.0           (kgC/m2)  litter carbon, shielded cellulose pool")
    lines.append(f"0.0           (kgC/m2)  litter carbon, lignin pool")
    lines.append(f"0.0           (kgC/m2)  soil carbon, fast microbial recycling pool")
    lines.append(f"0.0           (kgC/m2)  soil carbon, medium microbial recycling pool")
    lines.append(f"0.0           (kgC/m2)  soil carbon, slow microbial recycling pool")
    lines.append(f"0.0           (kgC/m2)  soil carbon, recalcitrant SOM (slowest)")
    lines.append("")

    # N_STATE section
    lines.append("N_STATE       (keyword) start of nitrogen state variable initialization block")
    lines.append(f"0.0           (kgN/m2)  litter nitrogen, labile pool")
    lines.append(f"0.0           (kgN/m2)  soil nitrogen, mineral pool")
    lines.append("")

    # OUTPUT_CONTROL section
    lines.append("OUTPUT_CONTROL   (keyword - do not remove)")
    lines.append(f"{args.output_prefix}     (text) prefix for output files")
    daily_flag = 0 if is_spinup else 1
    annual_flag = 0 if is_spinup else 1
    lines.append(f"{daily_flag}   (flag)  1 = write daily output   0 = no daily output")
    lines.append(f"0   (flag)  1 = monthly avg of daily variables  0 = no monthly avg")
    lines.append(f"{annual_flag}   (flag)  1 = annual avg of daily variables   0 = no annual avg")
    lines.append(f"{annual_flag}   (flag)  1 = write annual output  0 = no annual output")
    lines.append(f"1   (flag)  for on-screen progress indicator")
    lines.append("")

    # DAILY_OUTPUT section
    lines.append("DAILY_OUTPUT     (keyword)")
    if is_spinup:
        lines.append(f"0     (int) number of daily variables to output")
    else:
        daily_vars = STANDARD_DAILY_OUTPUT
        lines.append(f"{len(daily_vars)}     (int) number of daily variables to output")
        for idx, (var_id, var_name) in enumerate(daily_vars):
            lines.append(f"{var_id}     {idx} {var_name}")
    lines.append("")

    # ANNUAL_OUTPUT section
    lines.append("ANNUAL_OUTPUT    (keyword)")
    if is_spinup:
        lines.append(f"0               (int)   number of annual output variables")
    else:
        ann_vars = STANDARD_ANNUAL_OUTPUT
        lines.append(f"{len(ann_vars)}               (int)   number of annual output variables")
        for idx, (var_id, var_name) in enumerate(ann_vars):
            lines.append(f"{var_id}     {idx} {var_name}")
    lines.append("")

    lines.append("END_INIT      (keyword) indicates the end of the initialization file")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate BIOME-BGC .ini file")
    parser.add_argument("--met_file", required=True, help="Path to met data file")
    parser.add_argument("--met_header_lines", type=int, default=4,
                        help="Number of header lines in met file")
    parser.add_argument("--epc_file", required=True, help="Path to .epc file")
    parser.add_argument("--output_prefix", required=True,
                        help="Prefix for output files")
    parser.add_argument("--lat", type=float, required=True, help="Latitude (deg)")
    parser.add_argument("--elevation", type=float, default=500.0, help="Elevation (m)")
    parser.add_argument("--soil_depth", type=float, default=1.0,
                        help="Effective soil depth (m)")
    parser.add_argument("--sand", type=float, default=30.0, help="Sand %")
    parser.add_argument("--silt", type=float, default=50.0, help="Silt %")
    parser.add_argument("--clay", type=float, default=20.0, help="Clay %")
    parser.add_argument("--start_year", type=int, default=2000,
                        help="First simulation year")
    parser.add_argument("--n_met_years", type=int, required=True,
                        help="Number of met data years")
    parser.add_argument("--mode", choices=["spinup", "normal"], default="normal",
                        help="Simulation mode")
    parser.add_argument("--max_spinup_years", type=int, default=6000,
                        help="Max spinup years (only used in spinup mode)")
    parser.add_argument("--co2_ppm", type=float, default=380.0,
                        help="Constant CO2 concentration (ppm)")
    parser.add_argument("--co2_file", type=str, default=None,
                        help="Annual CO2 file path")
    parser.add_argument("--co2_vary", action="store_true",
                        help="Use varying CO2 from file")
    parser.add_argument("--ndep", type=float, default=0.0001,
                        help="N deposition (kgN/m2/yr)")
    parser.add_argument("--nfix", type=float, default=0.0004,
                        help="N fixation (kgN/m2/yr)")
    parser.add_argument("--albedo", type=float, default=0.2,
                        help="Site shortwave albedo")
    parser.add_argument("--init_snoww", type=float, default=0.0,
                        help="Initial snow water (kg/m2)")
    parser.add_argument("--init_soilw", type=float, default=0.5,
                        help="Initial soil water fraction of saturation")
    parser.add_argument("--restart_file", type=str, default=None,
                        help="Restart file path")
    parser.add_argument("--read_restart", action="store_true",
                        help="Read restart file for normal run")
    parser.add_argument("--write_restart", action="store_true",
                        help="Write restart file after normal run")
    parser.add_argument("--output", required=True, help="Output .ini file path")

    args = parser.parse_args()

    # Validate
    errors = validate_inputs(args)
    if errors:
        result = {"status": "error", "stage": "input_validation",
                  "errors": errors}
        print(json.dumps(result, indent=2))
        sys.exit(1)

    # Generate
    try:
        ini_content = generate_ini(args)
    except Exception as e:
        result = {"status": "error", "stage": "generation",
                  "message": str(e)}
        print(json.dumps(result, indent=2))
        sys.exit(2)

    # Write
    try:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(ini_content)
    except Exception as e:
        result = {"status": "error", "stage": "output",
                  "message": str(e)}
        print(json.dumps(result, indent=2))
        sys.exit(3)

    # Count sections for verification
    n_sections = sum(1 for line in ini_content.split("\n")
                     if "(keyword" in line.lower())

    result = {
        "status": "success",
        "output_file": str(out_path),
        "mode": args.mode,
        "met_file": args.met_file,
        "epc_file": args.epc_file,
        "start_year": args.start_year,
        "n_met_years": args.n_met_years,
        "lat": args.lat,
        "co2_ppm": args.co2_ppm,
        "soil_depth_m": args.soil_depth,
        "sand_pct": args.sand,
        "silt_pct": args.silt,
        "clay_pct": args.clay,
        "ini_sections": n_sections,
    }
    print(json.dumps(result, indent=2))
    sys.exit(0)


if __name__ == "__main__":
    main()
