#!/usr/bin/env python3
"""
Generate the main ParFlow Python run script.

Creates a complete pftools-based Python script that configures all ParFlow
solver keys and runs the simulation. Uses the ParFlow Python API (pftools).

Key solver parameters configured:
  - Richards equation (variably saturated flow)
  - Newton-Krylov nonlinear solver with PFMG preconditioner
  - Terrain-following grid (optional)
  - CLM coupling (optional)
  - Overland flow (kinematic or diffusive wave)

Usage:
    python generate_parflow_script.py \
        --domain_json outputs/parflow_run/domain/domain_definition.json \
        --subsurface_dir outputs/parflow_run/subsurface/ \
        --slope_dir outputs/parflow_run/topography/ \
        --ic_file outputs/parflow_run/ic_bc/initial_pressure.pfb \
        --run_name chaohe_test \
        --output_dir outputs/parflow_run/run/

Author: Jianyun Zhang Research Group, Hohai University
"""

import argparse
import json
import os
import sys
from datetime import datetime


def validate_inputs(domain_json):
    errors = []
    if not os.path.exists(domain_json):
        errors.append(f"Domain definition not found: {domain_json}")
    return errors


def process(domain_json, run_name, output_dir,
            start_date="2000-01-01", end_date="2010-12-31",
            dt_hours=1.0, dump_interval_hours=24,
            enable_clm=True, overland_flow="kinematic",
            terrain_following=True, p=1, q=1, r=1,
            subsurface_dir=None, slope_dir=None, ic_file=None,
            forcing_dir=None, clm_dir=None):
    """Generate ParFlow run script."""
    os.makedirs(output_dir, exist_ok=True)

    with open(domain_json) as f:
        domain = json.load(f)

    grid = domain["grid"]
    nx, ny, nz = grid["nx"], grid["ny"], grid["nz"]
    dx, dy = grid["dx"], grid["dy"]
    dz_layers = grid["dz_layers_m"]
    total_depth = grid["total_depth_m"]
    origin_x = domain["origin"]["x"]
    origin_y = domain["origin"]["y"]

    # Compute simulation hours
    start_dt = datetime.strptime(start_date, "%Y-%m-%d")
    end_dt = datetime.strptime(end_date, "%Y-%m-%d")
    total_hours = int((end_dt - start_dt).total_seconds() / 3600)
    total_steps = int(total_hours / dt_hours)
    dump_steps = int(dump_interval_hours / dt_hours)

    # dz as fractions for terrain-following
    if terrain_following:
        dz_fracs = [d / total_depth for d in dz_layers]
    else:
        dz_fracs = dz_layers

    # Generate the Python run script
    script_lines = [
        '#!/usr/bin/env python3',
        '"""',
        f'ParFlow run script for {run_name}',
        f'Generated by HydroCraft ParFlow KI',
        f'Domain: {nx}x{ny}x{nz}, dx={dx}m, total depth={total_depth}m',
        f'Period: {start_date} to {end_date}',
        '"""',
        '',
        'import os',
        'import sys',
        '',
        '# Add ParFlow install to PATH if needed',
        'PARFLOW_DIR = os.environ.get("PARFLOW_DIR", ',
        '    "KISSPATH_BINARIES/parflow/install")',
        'os.environ["PARFLOW_DIR"] = PARFLOW_DIR',
        'if os.path.join(PARFLOW_DIR, "bin") not in os.environ.get("PATH", ""):',
        '    os.environ["PATH"] = os.path.join(PARFLOW_DIR, "bin") + ":" + os.environ.get("PATH", "")',
        '',
        'try:',
        '    from parflow import Run',
        '    from parflow.tools.fs import mkdir, cp, get_absolute_path',
        'except ImportError:',
        '    print("ERROR: pftools not installed. Run: pip install pftools")',
        '    sys.exit(1)',
        '',
        f'run_name = "{run_name}"',
        f'run = Run(run_name, __file__)',
        '',
        '# ============================================================',
        '# Process / Computational Grid',
        '# ============================================================',
        f'run.Process.Topology.P = {p}',
        f'run.Process.Topology.Q = {q}',
        f'run.Process.Topology.R = {r}',
        '',
        '# ============================================================',
        '# Computational Grid',
        '# ============================================================',
        f'run.ComputationalGrid.Lower.X = {origin_x}',
        f'run.ComputationalGrid.Lower.Y = {origin_y}',
        f'run.ComputationalGrid.Lower.Z = 0.0',
        '',
        f'run.ComputationalGrid.NX = {nx}',
        f'run.ComputationalGrid.NY = {ny}',
        f'run.ComputationalGrid.NZ = {nz}',
        '',
        f'run.ComputationalGrid.DX = {dx}',
        f'run.ComputationalGrid.DY = {dy}',
        f'run.ComputationalGrid.DZ = {total_depth}  # scaled by dzScale',
        '',
    ]

    # Terrain-following grid dz scaling
    if terrain_following:
        script_lines += [
            '# Terrain-following grid: dz as fractions of total depth',
            'run.Solver.TerrainFollowingGrid = True',
            '',
            f'run.Cell.{0}.dzScale.Type = "nzList"',
            f'run.Cell.{0}.dzScale.nzListNumber = {nz}',
            '',
        ]
        for k, frac in enumerate(dz_fracs):
            script_lines.append(
                f'run.Cell.{k}.dzScale.Value = {frac:.6f}'
            )
        script_lines.append('')
    else:
        script_lines += [
            'run.Solver.TerrainFollowingGrid = False',
            '',
        ]

    # Domain and timing
    script_lines += [
        '# ============================================================',
        '# Timing',
        '# ============================================================',
        'run.TimingInfo.BaseUnit = 1.0  # hours',
        f'run.TimingInfo.StartCount = 0',
        f'run.TimingInfo.StartTime = 0.0',
        f'run.TimingInfo.StopTime = {total_hours}.0',
        f'run.TimingInfo.DumpInterval = {dump_interval_hours}',
        f'run.TimeStep.Type = "Constant"',
        f'run.TimeStep.Value = {dt_hours}',
        '',
        '# ============================================================',
        '# Domain',
        '# ============================================================',
        'run.Domain.GeomName = "domain"',
        '',
        '# Geometry input',
        'run.GeomInput.Names = "domain_input indicator_input"',
        'run.GeomInput.domain_input.GeomName = "domain"',
        'run.GeomInput.domain_input.InputType = "Box"',
        '',
        f'run.Geom.domain.Lower.X = {origin_x}',
        f'run.Geom.domain.Lower.Y = {origin_y}',
        'run.Geom.domain.Lower.Z = 0.0',
        f'run.Geom.domain.Upper.X = {origin_x + nx * dx}',
        f'run.Geom.domain.Upper.Y = {origin_y + ny * dy}',
        f'run.Geom.domain.Upper.Z = {total_depth}',
        '',
        '# ============================================================',
        '# Boundary Conditions (Patches)',
        '# ============================================================',
        'run.Geom.domain.Patches = "left right front back bottom top"',
        '',
        '# No-flow on bottom and sides',
        'run.BCPressure.PatchNames = "left right front back bottom top"',
        '',
        'for patch in ["left", "right", "front", "back", "bottom"]:',
        '    run.Patch.__getattr__(patch).BCPressure.Type = "FluxConst"',
        '    run.Patch.__getattr__(patch).BCPressure.Cycle = "constant"',
        '    run.Patch.__getattr__(patch).BCPressure.alltime.Value = 0.0',
        '',
        '# Top: overland flow boundary',
        'run.Patch.top.BCPressure.Type = "OverlandFlow"',
        'run.Patch.top.BCPressure.Cycle = "constant"',
        'run.Patch.top.BCPressure.alltime.Value = 0.0',
        '',
        '# ============================================================',
        '# Subsurface Properties',
        '# ============================================================',
        '# Permeability (CRITICAL: units are m/hr)',
        'run.Geom.domain.Perm.Type = "Constant"',
        'run.Geom.domain.Perm.Value = 0.001  # m/hr -- OVERRIDE with PFB files',
        '',
        '# Porosity',
        'run.Geom.domain.Porosity.Type = "Constant"',
        'run.Geom.domain.Porosity.Value = 0.4',
        '',
        '# Specific storage',
        'run.Geom.domain.SpecificStorage.Type = "Constant"',
        'run.Geom.domain.SpecificStorage.Value = 1.0e-4  # 1/m',
        '',
        '# van Genuchten (CRITICAL: alpha in 1/m, NOT 1/cm)',
        'run.Phase.RelPerm.Type = "VanGenuchten"',
        'run.Geom.domain.RelPerm.Alpha = 3.6  # 1/m',
        'run.Geom.domain.RelPerm.N = 1.56',
        '',
        'run.Phase.Saturation.Type = "VanGenuchten"',
        'run.Geom.domain.Saturation.Alpha = 3.6  # 1/m',
        'run.Geom.domain.Saturation.N = 1.56',
        'run.Geom.domain.Saturation.SRes = 0.078',
        'run.Geom.domain.Saturation.SSat = 1.0',
        '',
    ]

    # Overland flow
    script_lines += [
        '# ============================================================',
        '# Overland Flow (Manning\'s equation)',
        '# ============================================================',
        f'run.Solver.Nonlinear.UseStoppingCriteria = True',
    ]
    if overland_flow == "diffusive":
        script_lines.append('run.Solver.OverlandFlowDiffusive = 1')
    else:
        script_lines.append('run.Solver.OverlandKinematic = 1')
    script_lines += [
        '',
        'run.Mannings.Type = "Constant"',
        'run.Mannings.GeomNames = "domain"',
        'run.Mannings.Geom.domain.Value = 0.04',
        '',
    ]

    # Slope files
    script_lines += [
        '# ============================================================',
        '# Topographic Slopes',
        '# ============================================================',
        'run.TopoSlopesX.Type = "Constant"',
        'run.TopoSlopesX.GeomNames = "domain"',
        'run.TopoSlopesX.Geom.domain.Value = -0.001  # Override with PFB',
        '',
        'run.TopoSlopesY.Type = "Constant"',
        'run.TopoSlopesY.GeomNames = "domain"',
        'run.TopoSlopesY.Geom.domain.Value = -0.001  # Override with PFB',
        '',
    ]

    # CLM
    if enable_clm:
        script_lines += [
            '# ============================================================',
            '# CLM Coupling',
            '# ============================================================',
            'run.Solver.LSM = "CLM"',
            'run.Solver.CLM.CLMDumpInterval = 1',
            f'run.Solver.CLM.MetForcing = "1D"',
            f'run.Solver.CLM.MetFileName = "NLDAS"',
            f'run.Solver.CLM.MetFilePath = "./"',
            'run.Solver.CLM.IstepStart = 1',
            '',
        ]

    # Solver
    script_lines += [
        '# ============================================================',
        '# Solver Configuration',
        '# ============================================================',
        'run.Solver = "Richards"',
        'run.Solver.MaxIter = 25000',
        'run.Solver.Drop = 1e-20',
        'run.Solver.AbsTol = 1e-8',
        '',
        '# Nonlinear solver (Newton)',
        'run.Solver.Nonlinear.MaxIter = 300',
        'run.Solver.Nonlinear.ResidualTol = 1e-6',
        'run.Solver.Nonlinear.EtaChoice = "EtaConstant"',
        'run.Solver.Nonlinear.EtaValue = 0.01',
        'run.Solver.Nonlinear.UseJacobian = True',
        'run.Solver.Nonlinear.DerivativeEpsilon = 1e-14',
        'run.Solver.Nonlinear.StepTol = 1e-30',
        'run.Solver.Nonlinear.Globalization = "LineSearch"',
        '',
        '# Linear solver (PFMG from HYPRE)',
        'run.Solver.Linear.KrylovDimension = 100',
        'run.Solver.Linear.MaxRestarts = 5',
        'run.Solver.Linear.Preconditioner = "PFMG"',
        'run.Solver.Linear.Preconditioner.PFMG.MaxIter = 1',
        'run.Solver.Linear.Preconditioner.PFMG.NumPreRelax = 1',
        'run.Solver.Linear.Preconditioner.PFMG.NumPostRelax = 1',
        '',
        '# ============================================================',
        '# Output Control',
        '# ============================================================',
        'run.Solver.PrintSubsurfData = True',
        'run.Solver.PrintPressure = True',
        'run.Solver.PrintSaturation = True',
        'run.Solver.PrintMask = True',
        'run.Solver.PrintVelocities = False',
        'run.Solver.WriteSiloSubsurfData = False',
        'run.Solver.WriteSiloPressure = False',
        'run.Solver.WriteSiloSaturation = False',
        '',
        '# Initial conditions',
        'run.ICPressure.Type = "HydroStaticPatch"',
        'run.ICPressure.GeomNames = "domain"',
        'run.Geom.domain.ICPressure.Value = -5.0',
        'run.Geom.domain.ICPressure.RefGeom = "domain"',
        'run.Geom.domain.ICPressure.RefPatch = "bottom"',
        '',
        '# ============================================================',
        '# Run',
        '# ============================================================',
        f'run.run(working_directory="{output_dir}")',
        '',
        'print(f"ParFlow run {run_name} completed.")',
    ]

    # Write script
    script_path = os.path.join(output_dir, f"run_{run_name}.py")
    with open(script_path, "w") as f:
        f.write("\n".join(script_lines))
    os.chmod(script_path, 0o755)

    result = {
        "status": "success",
        "run_script": script_path,
        "run_name": run_name,
        "grid": {"nx": nx, "ny": ny, "nz": nz, "dx": dx, "dy": dy},
        "total_depth_m": total_depth,
        "simulation_hours": total_hours,
        "total_timesteps": total_steps,
        "dump_interval_hours": dump_interval_hours,
        "expected_output_files": total_steps // dump_steps,
        "mpi_topology": {"P": p, "Q": q, "R": r, "total_cores": p * q * r},
        "clm_enabled": enable_clm,
        "overland_flow": overland_flow,
        "terrain_following": terrain_following,
        "run_command": f"cd {output_dir} && python run_{run_name}.py",
        "mpi_run_command": f"cd {output_dir} && mpirun -np {p*q*r} parflow {run_name}",
    }
    return result


def main():
    parser = argparse.ArgumentParser(
        description="Generate ParFlow run script"
    )
    parser.add_argument("--domain_json", required=True)
    parser.add_argument("--run_name", required=True)
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--start_date", default="2000-01-01")
    parser.add_argument("--end_date", default="2010-12-31")
    parser.add_argument("--dt_hours", type=float, default=1.0)
    parser.add_argument("--dump_interval", type=int, default=24)
    parser.add_argument("--no_clm", action="store_true")
    parser.add_argument("--overland", choices=["kinematic", "diffusive"],
                        default="kinematic")
    parser.add_argument("--no_tfg", action="store_true")
    parser.add_argument("--p", type=int, default=1)
    parser.add_argument("--q", type=int, default=1)
    parser.add_argument("--r", type=int, default=1)
    args = parser.parse_args()

    errs = validate_inputs(args.domain_json)
    if errs:
        print(json.dumps({"status": "error", "errors": errs}))
        sys.exit(1)

    result = process(
        args.domain_json, args.run_name, args.output_dir,
        args.start_date, args.end_date, args.dt_hours, args.dump_interval,
        not args.no_clm, args.overland, not args.no_tfg,
        args.p, args.q, args.r,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
