"""Agent handoff — turn an unfinished install into something an agent can finish.

The installer is deterministic and will stop short on most models: 68 of the 127
packages are ``work_dir`` builds whose recipes vary by compiler, and almost none
of the required forcing data is ours to redistribute. Rather than fail, ``kiss``
writes the remaining work down in the file conventions each agent CLI already
reads, with the KI's own diagnostics attached.

This is the piece that makes a KI *self-installing*: the knowledge needed to
finish is already in the package, so the handoff just points at it.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

#: Where each agent CLI looks for project instructions. One canonical file,
#: mirrored — see DEPLOYMENT.md, which documents why this must not drift.
INSTRUCTION_FILES = {
    "CLAUDE.md": "Claude Code",
    "AGENTS.md": "OpenAI Codex",
    "QWEN.md": "Qwen Code",
    "GEMINI.md": "Gemini CLI",
}

#: Skill names must be kebab-case for harnesses that discover them.
#: DeepSeek Harness enforces exactly this pattern on its skill registry, and
#: rejects anything else outright — so a model directory like ``CLM5___CTSM``
#: must collapse to ``clm5-ctsm`` rather than ``clm5---ctsm``.
SKILL_NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def skill_slug(model: str, prefix: str = "kiss-") -> str:
    """Return a harness-legal skill name for ``model``."""
    body = re.sub(r"[^a-z0-9]+", "-", model.lower()).strip("-")
    slug = f"{prefix}{body}"
    if not SKILL_NAME_RE.match(slug):
        raise ValueError(f"cannot derive a legal skill name from {model!r} (got {slug!r})")
    return slug

SKILL_FRONTMATTER = """---
name: {slug}
description: >-
  Operate the {model} model through its Knowledge Infrastructure package.
  Use whenever the task involves running, configuring, calibrating or
  interpreting {model}. Covers setup completion, execution and output parsing.
---
"""


def _fmt_steps(result) -> str:
    lines = []
    for s in result.steps:
        lines.append(f"- **{s.name}** — {s.mark}")
        if s.detail:
            body = "\n".join("  " + ln for ln in s.detail.strip().splitlines()[:12])
            lines.append(body)
    return "\n".join(lines)


def _fmt_remaining(result, man) -> str:
    if result.ok:
        return ("Nothing outstanding — `preflight_check.py` passes. "
                "Run the reference case to confirm scientific output, then proceed.")
    out = ["The automated installer could not finish. Outstanding work:", ""]
    for s in result.failures:
        out.append(f"### {s.name}")
        out.append("```")
        out.append(s.detail.strip()[:1500] or "(no detail captured)")
        out.append("```")
        if s.commands:
            out.append("Commands already attempted:")
            out += [f"- `{c}`" for c in s.commands]
        out.append("")
    if man and man.agent_hint:
        out += ["### Guidance from the manifest", man.agent_hint, ""]
    return "\n".join(out)


def render(ki, result, man, cfg) -> str:
    """Build the canonical instruction document for one KI install."""
    meta = ki.meta or {}
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    triplets = ki.triplets.relative_to(ki.root) if ki.triplets else None

    doc = f"""# {ki.name} — Knowledge Infrastructure

Generated by `kiss init` on {stamp}. This file tells an AI coding agent how to
finish setting up and then operate **{ki.name}**.

## Mandatory execution policy

You MUST run the actual {ki.name} binary or package described in `SKILL.md`.
If it fails to build, import or execute:

1. Check `{triplets or 'diagnostics/'}` — the error may already be catalogued
   with a verified remedy.
2. Read the model's own documentation in `docs/` for expected formats and units.
3. Report the failure with full output.

You MUST NOT substitute a simplified formula, a regression fit, or a
hand-coded approximation for the real model. Doing so produces scientifically
invalid results and defeats the purpose of this package.

## What this model is

| | |
|---|---|
| Model | {meta.get('model_id', ki.name)} |
| Reference | {meta.get('reference') or 'see docs/REFERENCES.md'} |
| Implementation | {meta.get('impl_id') or '—'} {meta.get('version') or ''} |
| Language | {meta.get('language') or '—'} |
| Source | {meta.get('repo_url') or '—'} |
| Licence | {meta.get('license') or '—'} |
| Resolution | {meta.get('spatial') or '—'}, {meta.get('temporal') or '—'} |

## Where things are on this machine

```
KI package   {ki.root}
binaries     {cfg.roles.get('binaries')}
data         {cfg.roles.get('data')}
outputs      {cfg.roles.get('outputs')}
config       {cfg.root / 'kiss.toml'}
```

Paths inside this KI were written on the authoring machine. `kiss` relocates
them via `{cfg.relocation}` — do not hand-edit them to local paths; if a path
does not resolve, run `kiss doctor {ki.name}` and fix the mapping in `kiss.toml`.

## Install status

{_fmt_steps(result)}

## What you need to do

{_fmt_remaining(result, man)}

## Operating the model

Read **`SKILL.md`** in this directory before running anything — it is the
authoritative operating procedure, including unit conventions and known traps.
`dag.yaml` gives the machine-readable input/output contract.

Required forcing variables: {', '.join(ki.forcing_vars) or 'see dag.yaml'}

## Verification

```
{cfg.python} preflight_check.py
```

Every check must pass before you trust any simulation output.
"""
    return doc


def write(ki, result, man, cfg, dest: Path, *, skill: bool = True) -> list[Path]:
    """Write the instruction document under every agent's expected filename."""
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    body = render(ki, result, man, cfg)
    written: list[Path] = []

    canonical = dest / "CLAUDE.md"
    canonical.write_text(body, encoding="utf-8")
    written.append(canonical)

    for fname in INSTRUCTION_FILES:
        if fname == "CLAUDE.md":
            continue
        p = dest / fname
        try:
            if p.is_symlink() or p.exists():
                p.unlink()
            p.symlink_to(canonical.name)
        except OSError:
            p.write_text(body, encoding="utf-8")
        written.append(p)

    if skill:
        slug = skill_slug(ki.name)
        sk = dest / ".agents" / "skills" / slug / "SKILL.md"
        sk.parent.mkdir(parents=True, exist_ok=True)
        sk.write_text(SKILL_FRONTMATTER.format(slug=slug, model=ki.name) + "\n" + body,
                      encoding="utf-8")
        written.append(sk)

    return written
