#!/usr/bin/env python3
"""
Knowledge Infrastructure — Validated Tool
==========================================
Tool ID:      generate_agromanagement_yaml
Stage:        s4_agromanagement
Description:  Generate PCSE agromanagement YAML with crop calendar,
              optional irrigation and fertilization events.

              CRITICAL: crop_name and variety_name are CASE SENSITIVE.
              Use exact names from YAMLCropDataProvider.

Inputs:
  - CROP_NAME: crop name (must match parameter file, case sensitive)
  - VARIETY_NAME: variety name (must match parameter file, case sensitive)
  - CAMPAIGN_START: campaign start date (YYYY-MM-DD)
  - CROP_START_DATE: sowing/emergence date (YYYY-MM-DD)
  - CROP_START_TYPE: 'sowing' or 'emergence'
  - CROP_END_TYPE: 'maturity', 'harvest', or 'earliest'
  - MAX_DURATION: maximum simulation duration in days
  - OUTPUT_FILE: output YAML file path

Outputs:
  - Agromanagement YAML file

Exit codes:
  0 — success, 1 — input error, 2 — processing error, 3 — output error
"""

import sys
import os
import json
import logging
from pathlib import Path
from datetime import date

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

CROP_NAME = "wheat"
VARIETY_NAME = "Winter_wheat_101"
CAMPAIGN_START = "2000-10-01"
CROP_START_DATE = "2000-10-15"
CROP_START_TYPE = "sowing"
CROP_END_TYPE = "maturity"
MAX_DURATION = 365
OUTPUT_FILE = ""

# Optional irrigation events: list of (date_str, amount_cm, efficiency)
IRRIGATION_EVENTS = []  # e.g., [("2001-04-15", 3.0, 0.7)]


def validate_inputs():
    errors = []
    if not CROP_NAME:
        errors.append("CROP_NAME not set")
    if not VARIETY_NAME:
        errors.append("VARIETY_NAME not set")
    if not CAMPAIGN_START:
        errors.append("CAMPAIGN_START not set")
    if not CROP_START_DATE:
        errors.append("CROP_START_DATE not set")
    if CROP_START_TYPE not in ("sowing", "emergence"):
        errors.append(f"CROP_START_TYPE must be 'sowing' or 'emergence', got '{CROP_START_TYPE}'")
    if CROP_END_TYPE not in ("maturity", "harvest", "earliest"):
        errors.append(f"CROP_END_TYPE must be 'maturity', 'harvest', or 'earliest', got '{CROP_END_TYPE}'")
    if MAX_DURATION <= 0:
        errors.append(f"MAX_DURATION must be > 0, got {MAX_DURATION}")
    if not OUTPUT_FILE:
        errors.append("OUTPUT_FILE not set")

    # Date ordering
    try:
        campaign = date.fromisoformat(CAMPAIGN_START)
        crop_start = date.fromisoformat(CROP_START_DATE)
        if campaign > crop_start:
            errors.append(f"CAMPAIGN_START ({CAMPAIGN_START}) must be <= CROP_START_DATE ({CROP_START_DATE})")
    except ValueError as e:
        errors.append(f"Date parse error: {e}")

    if errors:
        for e in errors:
            logger.error(e)
        sys.exit(1)
    logger.info("Input validation passed.")


def process():
    """Generate agromanagement YAML."""
    import yaml

    campaign_date = date.fromisoformat(CAMPAIGN_START)
    crop_start = date.fromisoformat(CROP_START_DATE)

    # Build crop calendar
    crop_calendar = {
        'crop_name': CROP_NAME,
        'variety_name': VARIETY_NAME,
        'crop_start_date': crop_start,
        'crop_start_type': CROP_START_TYPE,
        'crop_end_date': None,
        'crop_end_type': CROP_END_TYPE,
        'max_duration': MAX_DURATION,
    }

    # Build timed events (irrigation)
    timed_events = None
    if IRRIGATION_EVENTS:
        events_table = []
        for date_str, amount, efficiency in IRRIGATION_EVENTS:
            event_date = date.fromisoformat(date_str)
            events_table.append({event_date: {'amount': amount, 'efficiency': efficiency}})

        timed_events = [{
            'event_signal': 'irrigate',
            'name': 'irrigation schedule',
            'comment': 'generated by generate_agromanagement_yaml tool',
            'events_table': events_table,
        }]

    # Assemble agromanagement
    agro = [{
        campaign_date: {
            'CropCalendar': crop_calendar,
            'TimedEvents': timed_events,
            'StateEvents': None,
        }
    }]

    # Write YAML
    os.makedirs(os.path.dirname(OUTPUT_FILE) or '.', exist_ok=True)
    with open(OUTPUT_FILE, 'w') as f:
        yaml.dump(agro, f, default_flow_style=False, allow_unicode=True)

    logger.info(f"Created agromanagement YAML: {OUTPUT_FILE}")
    logger.info(f"  Crop: {CROP_NAME} / {VARIETY_NAME}")
    logger.info(f"  Campaign: {CAMPAIGN_START}, Sowing: {CROP_START_DATE}")
    logger.info(f"  Max duration: {MAX_DURATION} days")

    # Verify by re-reading
    with open(OUTPUT_FILE) as f:
        loaded = yaml.safe_load(f)
    assert isinstance(loaded, list), "Agromanagement must be a list"
    assert len(loaded) > 0, "Agromanagement is empty"

    return OUTPUT_FILE


if __name__ == "__main__":
    if len(sys.argv) >= 8:
        CROP_NAME = sys.argv[1]
        VARIETY_NAME = sys.argv[2]
        CAMPAIGN_START = sys.argv[3]
        CROP_START_DATE = sys.argv[4]
        CROP_START_TYPE = sys.argv[5]
        MAX_DURATION = int(sys.argv[6])
        OUTPUT_FILE = sys.argv[7]

    validate_inputs()
    try:
        result = process()
    except Exception as e:
        logger.error(f"Processing failed: {e}")
        sys.exit(2)

    print(json.dumps({"status": "success", "output_file": result}))
    sys.exit(0)
